/// This class contains all the App Text in String formats.
class TTextsPrivacy {

  // -- 1 General provisions texts
  static const String generalProvisionsPrivacy = "1. General provisions";
  static const String termsPrivacy = " This Policy regarding the processing of personal data (hereinafter referred to as the Policy) defines the goals, establishes the procedure and conditions for the processing of personal data, measures aimed at protecting personal data, and also contains information about the rights of persons to whom the relevant personal data relates to Easy Shoppin LLC ( hereinafter referred to as the Society).";
  static const String processesPersonalAccordance = " The Company processes personal data in accordance with the requirements of the Federal Law of the Russian Federation dated July 27, 2006 No. 152-FZ “On Personal Data” and other regulatory legal acts of the Russian Federation governing legal relations in the field of personal data processing.";
  static const String policyAppliesSubjects = "The Policy applies to all personal data of personal data subjects specified in clauses 4.1.1., 4.1.2. Policies processed in the Company with and without the use of automation tools.";
  static const String policyAppliesRelated = " The Policy applies to all actions related to the processing of personal data by the Company on the information resource, which is accessed via the domain name “*.wb.ru”, “*.easyshoppin.ru”, or using the Company’s mobile application (hereinafter referred to as the “Site”).";
  static const String subjectPersonalPolicy = " If the subject of personal data objects to the processing of personal data by the Company in accordance with the Policy, the subject of personal data has the right to refuse to use the Site and/or send an appropriate request to the Company. In this case, the functionality of the Site, including registration of a personal account, will not be provided.";
  static const String processingPersonalCarried = " The processing of personal data of the subject of personal data is carried out with the consent of the subject of personal data to the processing of his personal data, as well as without obtaining consent in cases provided for by the legislation of the Russian Federation.";
  static const String policyComesGeneralDirector = " This Policy comes into force from the moment of its approval by the General Director of the Organization and is valid indefinitely until it is replaced by a new Policy.";
  static const String companyUnilaterallyChange = " The Company has the right to unilaterally change the terms of the Policy.";
  static const String policyFreelyInternet = " Due to the fact that the text of the Policy is freely available on the Internet, the subject of personal data must independently monitor changes made to the Policy.";
  static const String policyAppliesReceived = " This Policy applies to personal data received both before and after the entry into force of this Policy.";
  static const String internalControlCompany = " Internal control over compliance with the requirements of the Policy is carried out by the person responsible for organizing the processing of personal data in the Company.";
  static const String followingTermsPolicy = " The following terms are used in the Policy:";
  static const String automatedProcessingPersonal = " Automated processing of personal data - processing of personal data using computer technology.";
  static const String blockingTemporaryCessation = " Blocking is a temporary cessation of processing of personal data (except for cases where processing is necessary to clarify personal data).";
  static const String securityPersonalData = " Security of personal data is the state of security of personal data, characterized by the ability of users of personal data information systems, personal data operators, technical means and information technologies to ensure the confidentiality, integrity and availability of personal data when processed in personal data information systems.";
  static const String biometricPersonalData = " Biometric personal data is data that characterizes the physiological and biological characteristics of a person, on the basis of which his identity can be established.";
  static const String federalLaw = " Law - Federal Law of the Russian Federation dated July 27, 2006 No. 152-FZ “On Personal Data”.";
  static const String registeredBuyer = " Registered user (Buyer) - an individual who has a Site user ID (registered on the Site) and uses the Site in accordance with the Rules for using the Easy Shoppin trading platform, located at https://www.easyshoppin.ru/services/pravila- polzovaniya-torgovoy-ploshchadkoy.";
  static const String depersonalization = " Depersonalization - actions as a result of which it becomes impossible to determine the ownership of personal data by a specific subject of personal data without the use of additional information.";
  static const String processingPersonalData = " Processing of personal data - any action (operation) or set of actions (operations) performed with or without the use of automation tools with personal data, as well as through mixed processing, including collection, recording, systematization, accumulation, storage, clarification (updating , change), extraction, use, transfer (distribution, provision, access), depersonalization, blocking, deletion, destruction of personal data.";
  static const String society = " Society - Easy Shoppin LLC.";
  static const String operatorIndependently = " Operator - a person who, independently or jointly with other persons, organizes and (or) carries out the processing of personal data, as well as determining the purposes of processing personal data, the composition of personal data to be processed, actions (operations) performed with personal data. For the purposes of this Policy, the Company, when processing personal data, is an operator, unless otherwise expressly stated in the Policy.";
  static const String confidentialityPersonalData = " Confidentiality of personal data is a mandatory requirement for the Company or any other person who has access to personal data not to disclose to third parties or distribute personal data without the consent of the subject of personal data or the presence of another legal basis provided for by federal law.";
  static const String personalData  = " Personal data - any information relating to a directly or indirectly identified or identifiable individual (subject of personal data).";
  static const String individualUsingServices = " User - an individual using the services of the Site (Internet user).";
  static const String websiteCompanyInformation = " The website is the Company’s information resource on the Internet, accessed via the domain name “*.wb.ru”, “*.easyshoppin.ru”, or using the Company’s mobile application.";
  static const String specialCategoryPersonalData = " A special category of personal data is information relating to race, nationality, political views, religious or philosophical beliefs, health status, intimate life.";
  static const String provisionActionsAimed = " Provision - actions aimed at disclosing personal data to a certain person or a certain group of persons.";
  static const String distributionActionsAimed = " Distribution - actions aimed at disclosing personal data to an indefinite number of persons.";
  static const String individualDirectly = " Personal data subject is an individual directly or indirectly identified or determined on the basis of personal data relating to him.";
  static const String destructionPersonalData = " Destruction of personal data - actions as a result of which it becomes impossible to restore the content of personal data in the personal data information system and (or) as a result of which material media of personal data are destroyed.";
  static const String cookiesCompanyContaining = " Cookies are text files available to the Company containing information about the device (IP address of the device), browser, application version, and stored in the browser of the computer (mobile device) of the User or Registered User when they visit the Site. The collection of cookies can be configured or disabled independently in the settings of the browser used.";
  static const String nicknameWebsite = " Pseudonym (nickname) is the name of the user (PDN subject) in a service, on a website, etc., which the user comes up with independently during registration.";
  static const String otherTermsNotMentioned = " Other terms not mentioned above are used in the meaning established by regulatory legal acts of the Russian Federation, documents and local acts of the Company.";

  // -- 2 Purposes of processing personal data texts
  static const String purposesPersonalData = "2. Purposes of processing personal data";
  static const String companyProcessesData  = " The Company processes personal data for the following purposes:";
  static const String registrationPersonalAccount = " Registration and use of your personal account to place orders on the Site, as well as to receive informational and advertising mailings.";
  static const String personalAccountRegisteredUser = " Use of a personal account by a Registered User on the Site by filling out information about yourself; placing orders (including payment and delivery of orders), tracking the status of an order, writing reviews about products, drawing up requests regarding work on the Site through a special form in the Registered User’s personal account, exercising the possibility of returning goods or funds (within the warranty period).";
  static const String providingPossibilityBooking = " Providing the possibility of booking (purchasing) air and ground transport tickets on the Site.";
  static const String providingCustomsClearance = " Providing data for customs clearance and delivery of goods, in case of ordering goods from abroad.";
  static const String providingDataCompletingTraining = " Providing data for completing training courses published by third parties on the Company’s Website.";
  static const String usingSiteCapabilities = " Using the Site's capabilities to make audio and video calls";

  // -- 3 Legal grounds for processing personal data texts
  static const String legalGrounds  = "3. Legal grounds for processing personal data";
  static const String carriedCompany = " The processing of personal data is carried out by the Company on the following legal grounds:";
  static const String consentSubjectPersonal = "- the processing of personal data is carried out with the consent of the subject of personal data to the processing of his personal data, which the subject provides by active action, including putting a mark in the interface opposite the phrase: “I agree to the processing of personal data, with the rules for using the trading platform and returning”;";
  static const String internationalTreaty = "- processing of personal data is necessary to achieve the goals provided for by an international treaty of the Russian Federation or law, to implement and fulfill the functions, powers and responsibilities assigned by the legislation of the Russian Federation to the operator";
  static const String executionAgreement = "- the processing of personal data is necessary for the execution of an agreement to which the subject of personal data is a party or beneficiary or guarantor, as well as for concluding an agreement on the initiative of the subject of personal data or an agreement under which the subject of personal data will be a beneficiary or guarantor. An agreement concluded with a personal data subject cannot contain provisions limiting the rights and freedoms of the personal data subject;";
  static const String legitimateInterests = "- the processing of personal data is necessary to exercise the rights and legitimate interests of the operator or third parties, provided that the rights and freedoms of the subject of personal data are not violated.";

  // -- 4 Categories of personal data processed, categories of personal data subjects texts
  static const String categoriesProcessed = "4. Categories of personal data processed, categories of personal data subjects";
  static const String followingPersonalDataSubjects = " The Company processes personal data of the following personal data subjects:";
  static const String individualsUsers = " Individuals - Users, in accordance with the purpose of processing specified in paragraphs. 2.1.1., 2.1.6.";
  static const String individualsRegisteredUsers = " Individuals - Registered users, in accordance with the purposes of processing specified in paragraphs. 2.1.2., 2.1.3., 2.1.4., 2.1.5., 2.1.6.";
  static const String followingCategories = " The Company processes the following categories of personal data of personal data subjects:";
  static const String policyTelephoneNumber = " As part of achieving the goals specified in clause 2.1.1 of the Policy - telephone number.";
  static const String policyUserData1 = " As part of achieving the goals specified in clause 2.1.2 of the Policy - Site user ID; phone number; nickname (nickname); E-mail address; floor; order delivery address; Payment Methods; fiscal receipt; information about purchased goods.";
  static const String policyUserData2 = " As part of achieving the goal specified in clause 2.1.3 of the Policy - full name; Date of Birth; citizenship; floor; details of identity documents; phone number; E-mail address; Site user ID.";
  static const String policyUserData3 = " As part of achieving the goal specified in clause 2.1.4 of the Policy - full name; Date of Birth; details of identity documents; phone number; TIN; order delivery address; order list; Site user ID.";
  static const String policyUserData4 = " As part of achieving the goal specified in clause 2.1.5 of the Policy - full name; phone number; E-mail address; information about taking courses in educational institutions (regional department and/or association/union), Site user ID.";
  static const String policyUserData5 = " As part of achieving the goal specified in clause 2.1.6 of the Policy - pseudonym (nickname); video recordings (without the purpose of identification).";

  // -- 5 Procedure and conditions for processing personal data texts
  static const String procedureConditions = "5. Procedure and conditions for processing personal data";
  static const String companyProcessesEnsures = " The Company processes and ensures the security of personal data for the implementation of the functions, powers and responsibilities assigned to the Company by the legislation of the Russian Federation, including, but not limited to, in accordance with the Constitution of the Russian Federation, federal laws, in particular Federal Law No. 152-FZ of July 27 2006 “On Personal Data”, by-laws, other defining cases and features of the processing of said personal data by the federal laws of the Russian Federation, as well as the Civil Code of the Russian Federation, Law of the Russian Federation No. 2300-1 of February 7, 1992 “On the Protection of Consumer Rights” , as well as the charter and local acts of the Company.";
  static const String processesAutomationTools = " The Company processes personal data using automation tools, including collection, recording, systematization, accumulation, storage, clarification (updating, changing), extraction, use, transfer (provision, access, distribution), depersonalization, blocking, deletion, destruction of personal data within the time period necessary to achieve the purposes of processing personal data.";
  static const String registeredUserConsents  = " The registered user consents to the processing of personal data, valid from the date he begins using his personal account on the Site, and for a period of 30 days after the date of withdrawal of consent and deletion of the user’s personal account on the Site, since 30 days are necessary for the Company to complete the processing of all goods , returned by the user. Exceptions to this period are provided by the provisions of the Law.";
  static const String notProcessSpecialCategories = " The Company does not process special categories of personal data and biometric personal data, except in cases where the processing of personal data is due to current business objectives, with the obligatory consent of the subject of personal data to the processing of personal data, or is necessary in accordance with the requirements of the legislation of the Russian Federation.";
  static const String rightEntrustProcessing = " The Company has the right to entrust the processing of personal data to third parties - processors - on the basis of contracts concluded with these persons and with the consent of the subject of personal data. If the Company entrusts the processing of personal data to another person, the Company is responsible to the subject of personal data for the actions of the said person. The person processing personal data on behalf of the Company is responsible for the security of personal data and compliance with the requirements of the Law to the Company. A person processing personal data on behalf of the Operator is not required to obtain the consent of the subject of personal data to process his personal data.";
  static const String personsProcessingPersonal = " Persons processing personal data on the basis of an agreement concluded with the Company (operator’s instructions), under the terms of the agreements concluded with them, undertake to comply with the principles, rules for the processing and protection of personal data provided for by current legislation.";
  static const String entrustProcessingPersonal = " The Company has the right to entrust the processing of personal data, or to transfer the personal data specified in paragraphs. 4.2.1. — 4.2.7. Policy, to third parties only if there are proper grounds for processing, and also on the condition that the data will be transferred to the minimum extent necessary to achieve the specified purposes, and third parties will take measures aimed at complying with the requirements for ensuring the security of personal data to achieve the following purposes:";
  static const String deliveryOrdersReturnGoods = " Delivery of orders and return of goods.";
  static const String receiptProcessingTransfer = " Receipt, processing and transfer of funds.";
  static const String carryingCustomsClearance = " Carrying out customs clearance and delivery of goods in case of ordering goods from abroad.";
  static const String groundTransportTickets = " Issuing air and ground transport tickets, hotel reservations.";
  static const String completingTrainingCourses = " Completing training courses published by third parties on the Company’s Website.";
  static const String policiesInstructionsTransfer = " In accordance with clause 5.7. Policies, instructions for processing and transfer of personal data are carried out on the basis of agreements concluded by the Company with the following third parties: legal entities providing services to the Company, including ensuring security, delivery and customs clearance of goods; legal entities providing educational and other services to Registered users of the Site. The assignment of processing and transfer of personal data is carried out in cases provided for by agreements in which the subject of personal data is a party, beneficiary or guarantor, in accordance with the Rules for using the Easy Shoppin trading platform, located at https://www.easyshoppin.ru/services/pravila -polzovaniya-torgovoy-ploshchadkoy.";
  static const String obligesPersonsAuthorized = " The Company undertakes and obliges persons authorized to process personal data not to disclose to third parties or distribute personal data without the consent of the subject of personal data, unless otherwise provided by federal law.";
  static const String destroyingPersonalData = " The procedure for destroying personal data on media containing personal data, including external/removable electronic media, paper media and in personal data information systems, is determined by the Company in its internal documents and local regulations.";
  static const String companyNotVerify = " The Company does not verify (does not have the ability to verify) the relevance and accuracy of the information provided by personal data subjects obtained through the Site. The Company proceeds from the fact that subjects of personal data provide reliable and sufficient personal data and keep them up to date.";
  static const String controlComplianceTerms = " The Company does not control compliance with the terms of confidentiality and processing of personal data of personal data subjects by owners or users of other sites to which the subject of personal data can click on links available on the Site, and is not responsible for the actions or inactions of owners or users of such sites in the field of processing personal data. data and privacy.";
  static const String representativesAuthorized = " Representatives of authorized government bodies (including regulatory, supervisory, law enforcement, inquiry and investigation) receive access to personal data processed in the Company to the extent and in the manner established by the legislation of the Russian Federation.";
  static const String companyNecessaryLegal = " The Company takes the necessary legal, organizational and technical measures to protect personal data from unauthorized or accidental access, destruction, modification, blocking, copying, provision, distribution of personal data, as well as from other unlawful actions in relation to personal data in accordance with legal requirements Russian Federation and internal documents. Ensuring the security of personal data and fulfillment of the Company’s obligations in accordance with the Law is achieved, including:";
  static const String determiningThreatsSecurity = " Determining threats to the security of personal data during their processing in personal data information systems.";
  static const String applicationOrganizational = " Application of organizational and technical measures to ensure the security of personal data during their processing in personal data information systems necessary to fulfill the requirements for the protection of personal data, the implementation of which ensures the levels of personal data security established by the Government of the Russian Federation.";
  static const String assessingEffectiveness = " Assessing the effectiveness of measures taken to ensure the security of personal data before putting into operation the personal data information system.";
  static const String appointmentPersonResponsible = " Appointment of a person responsible for organizing the processing of personal data.";
  static const String publicationCompanyDocuments = " Publication by the Company of documents defining the Company's policy regarding the processing of personal data, local acts on the processing of personal data, defining for each purpose of processing personal data the categories and list of processed personal data, categories of subjects whose personal data is processed, methods, terms of their processing and storage , the procedure for the destruction of personal data upon achieving the purposes of their processing or upon the occurrence of other legal grounds, as well as local acts establishing procedures aimed at preventing and identifying violations of the legislation of the Russian Federation, eliminating the consequences of such violations. Such documents and local acts cannot contain provisions limiting the rights of personal data subjects, as well as imposing on the Company powers and obligations not provided for by the legislation of the Russian Federation.";
  static const String carryingInternalControl = " Carrying out internal control and (or) audit of compliance of personal data processing with the Law and regulatory legal acts adopted in accordance with it, requirements for the protection of personal data, the Company’s policy regarding the processing of personal data, internal documents of the Company.";
  static const String familiarizationCompanys = " Familiarization of the Company's employees directly involved in the processing of personal data with the provisions of the legislation of the Russian Federation on personal data, including requirements for the protection of personal data, documents defining the Company's policy regarding the processing of personal data, local regulations on the processing of personal data, and (or ) training of these employees.";
  static const String assessmentAccordance = " Assessment of harm in accordance with the requirements established by the authorized body for the protection of the rights of personal data subjects that may be caused to personal data subjects in the event of a violation of this Federal Law, the relationship between this harm and the measures taken by the operator aimed at ensuring the fulfillment of the obligations provided for by this Federal Law.";
  static const String detectionFactsUnauthorized = " Detection of facts of unauthorized access to personal data and taking measures, including measures to detect, prevent and eliminate the consequences of computer attacks on personal data information systems and to respond to computer incidents in them.";
  static const String controlSecurityPersonalData = " Control over the measures taken to ensure the security of personal data and the level of security of personal data information systems.";
  static const String companyStops = " The Company stops processing personal data and destroys it in the following cases:";
  static const String liquidationCompany = " liquidation of the Company;";
  static const String reorganizationCompany = " reorganization of the Company, entailing the termination of its activities;";
  static const String terminationLegalGrounds = " termination of the legal grounds for processing personal data and/or achieving the purposes of processing personal data;";
  static const String revocationConsentSubject = " revocation of the consent of the subject of personal data to the processing of personal data.";
  static const String storagePersonalData = " The storage of personal data is carried out by the Company in a form that allows identifying the subject of personal data no longer than required by the purposes of processing personal data and in accordance with the provisions of the Law.";
  static const String collectingPersonalData = " When collecting personal data, the Company ensures recording, systematization, accumulation, storage, clarification (updating, changing), retrieval of personal data of citizens of the Russian Federation using databases located on the territory of the Russian Federation, except for cases provided for by the Law.";
  static const String procedureDestruction= " The procedure for the destruction of personal data on media containing personal data, including external/removable electronic media, paper media and personal data information systems, is being developed in accordance with the Order of the Federal Service for Supervision of Communications, Information Technology and Mass Communications dated October 28 2022 No. 179 “On approval of the Requirements for confirming the destruction of personal data” and is enshrined in the Rules for the destruction and depersonalization of personal data of the Company.";
  static const String deletePersonalAccount = " Consent to the processing of personal data can be withdrawn by the subject of personal data, including by clicking on the special “Delete personal account” button on the Site.";

  // -- 6 Responses to requests from subjects for access to personal data texts
  static const String responsesRequests = "6. Responses to requests from subjects for access to personal data";
  static const String collectingPersonalDataCompany = " When collecting personal data, the Company is obliged to provide the subject of personal data, at his request, with the information provided for in Part 7 of Article 14 of the Law.";
  static const String demandCompanyClarification = " The subject of personal data has the right to demand from the Company clarification of his personal data, blocking or destruction of it if the personal data is incomplete, outdated, inaccurate, illegally obtained or is not necessary for the stated purpose of processing, as well as take measures provided by law to protect his rights.";
  static const String stopTransfer = " The subject of personal data has the right to apply to the Company with a request to stop the transfer (distribution, provision, access) of his personal data, previously authorized by the Subject of personal data, in terms of the specified actions for distribution, in case of non-compliance with the provisions of Article 10.1 of the Law, or to apply with such a demand to the court . The Company is obliged to stop the transfer (distribution, provision, access) of personal data within three working days from the receipt of the request of the subject of personal data or within the period specified in the court decision that has entered into legal force, and if such a period is not specified in the court decision, then within three working days from the moment the court decision enters into legal force.";
  static const String appealInactionCompany = " The subject of personal data has the right to appeal the actions or inaction of the Company to the Federal Service for Supervision in the Sphere of Communications, Information Technologies and Mass Communications (Roskomnadzor) or in court if the subject of personal data believes that the Company is processing his personal data in violation of the requirements of the Law or otherwise violates his rights and freedoms.";
  static const String protectLegitimateInterests = " To exercise his rights and protect legitimate interests, the subject of personal data has the right to contact the Company. To send official requests to the Company, you must use the contact information specified in paragraphs. 6.17., 6.18. Politicians.";
  static const String unlawfulProcessing = " If unlawful processing of personal data is detected upon application by the subject of personal data or his representative or at the request of the subject of personal data or his representative or the authorized body for the protection of the rights of personal data subjects, the operator is obliged to block unlawfully processed personal data relating to this subject of personal data, or ensure their blocking (if the processing of personal data is carried out by another person acting on behalf of the operator) from the moment of such an appeal or receipt of the specified request for the period of verification.";
  static const String inaccuratePersonalData = " If inaccurate personal data is identified when contacting the subject of personal data or his representative or at their request or at the request of the authorized body for the protection of the rights of subjects of personal data, the operator is obliged to block personal data relating to this subject of personal data or ensure their blocking (if processing personal data is carried out by another person acting on behalf of the operator) from the moment of such application or receipt of the specified request for the period of verification, if blocking of personal data does not violate the rights and legitimate interests of the subject of personal data or third parties.";
  static const String factInaccuracyPersonalData = " If the fact of inaccuracy of personal data is confirmed, the Company, on the basis of information provided by the subject of personal data or his representative or an authorized body for the protection of the rights of subjects of personal data, or other necessary documents, is obliged to clarify the personal data or ensure their clarification (if the processing of personal data is carried out by another person, acting on behalf of the operator) within seven working days from the date of submission of such information and remove the blocking of personal data.";
  static const String purposeProcessingPersonalData = " If the purpose of processing personal data is achieved, the Company is obliged to stop processing personal data or ensure its termination (if the processing of personal data is carried out by another person acting on behalf of the operator) and destroy personal data or ensure its destruction (if the processing of personal data is carried out by another person acting on behalf of the operator). on behalf of the Company) within a period not exceeding thirty days from the date of achieving the purpose of processing personal data, unless otherwise provided by an agreement to which the subject of personal data is a party, beneficiary or guarantor, another agreement between the Company and the subject of personal data, or if the Company has no right carry out the processing of personal data without the consent of the subject of personal data on the grounds provided for by the Law or other federal laws.";
  static const String withdrawsConsent  = " If the subject of personal data withdraws consent to the processing of his personal data, the Company is obliged to stop processing them or ensure the termination of such processing (if the processing of personal data is carried out by another person acting on behalf of the Company) and in the event that the preservation of personal data is no longer required for the purposes of processing personal data, destroy personal data or ensure their destruction (if the processing of personal data is carried out by another person acting on behalf of the Company) within a period not exceeding thirty days from the date of receipt of the said response, unless otherwise provided by the agreement to which the beneficiary or guarantor is a party which is the subject of personal data, another agreement between the Company and the subject of personal data, or if the Company does not have the right to process personal data without the consent of the subject of personal data on the grounds provided for by the Law or other federal laws.";
  static const String subjectPersonalDataApplies = " If a subject of personal data applies to the Company with a request to stop processing personal data, the Company is obliged, within a period not exceeding ten working days from the date the Company receives the corresponding request, to stop processing them or ensure the termination of such processing (if such processing is carried out by the person processing personal data). data), except for the cases provided for in paragraphs 2 - 11 of part 1 of Article 6, part 2 of Article 10 and part 2 of Article 11 of the Law. This period may be extended, but not more than by five working days, if the operator sends a motivated notification to the personal data subject indicating the reasons for extending the period for providing the requested information.";
  static const String possibleDestroyPersonalData = " If it is not possible to destroy personal data within the period established by the Law, the Company blocks such personal data or ensures their blocking (if the processing of personal data is carried out by another person acting on behalf of the operator) and ensures the destruction of personal data within a period of no more than six months , unless another period is established by federal laws.";
  static const String personalDataProcessed = " If the personal data processed by the Company for the purposes of purchasing air and (or) ground transport tickets is not received from the subject of personal data, then such personal data is considered by the Company to have been legally received by the Registered User of the Site, transferring to the Company the personal data of the subject of personal data. Before processing such personal data, the Company is obliged to notify the subject of personal data and provide him with the following information:";
  static const String nameAddressCompany = " Name and address of the Company or its representative.";
  static const String purposeProcessingPersonal = " Purpose of processing personal data and its legal basis.";
  static const String listPersonalData = " List of personal data.";
  static const String intendedUsersPersonalData = " Intended users of personal data.";
  static const String rightsSubjectPersonalData = " Rights of the subject of personal data established by law.";
  static const String sourcePersonalData = " Source of personal data.";
  static const String companyReleased = " The Company is released from the obligation to provide the subject of personal data with the information provided for in the relevant paragraphs of this Policy in cases where:";
  static const String personalDataNotified = " The subject of personal data is notified of the processing of his personal data by the Company.";
  static const String personalDataAuthorized = " The processing of personal data authorized by the subject of personal data for distribution is carried out in compliance with the prohibitions and conditions provided for in Article 10.1 of the Law.";
  static const String personalDataStatistical = " The Company processes personal data for statistical or other research purposes, unless the rights and legitimate interests of the subject of personal data are violated.";
  static const String relevantParagraphs = " Providing the subject of personal data with the information provided for in the relevant paragraphs of this Policy violates the rights and legitimate interests of third parties.";
  static const String companyEnsuresRecording = " When collecting personal data, the Company ensures recording, systematization, accumulation, storage, clarification (updating, changing), retrieval of personal data of citizens of the Russian Federation using databases located on the territory of the Russian Federation, except for cases provided for by the Law.";
  static const String investigatesViolations = " The Company considers any requests and complaints from subjects of personal data, investigates violations and takes all necessary measures to immediately eliminate them and resolve disputes out of court. The processing of personal data authorized by the subject of personal data for distribution is carried out in compliance with the prohibitions and conditions provided for in Article 10.1 of the Law.";
  static const String informationRegardingProcessing = " A written request from a personal data subject to provide information regarding the processing of his personal data must contain the mandatory information established by Part 3 of Article 14 of the Law, including the telephone number used to enter the Site. A written appeal (request) is sent to the legal address of the Company: 142181, Moscow region, Podolsk, Koledino village, Territory Industrial Park Koledino, 6, building 1.";
  static const String electronicDocument = " The request can also be sent by the subject of personal data in the form of an electronic document and signed with an electronic signature in accordance with the legislation of the Russian Federation. To obtain information about your personal data, familiarize yourself with it, clarify it, block or destroy it, or withdraw consent to its processing, requests can be sent to the email address: sales@wildberries.ru.";
  static const String interactionOtherIssues = " Interaction on other issues related to the processing of personal data by the Company is also carried out using the following contact information: postal address (142181, Moscow region, Podolsk, Koledino village, Territory Industrial Park Koledino, 6, building 1) and / or email address (sales@wildberries.ru).";
}
