/// This class contains all the App Text in String formats.
class TTextsRulesTrading {

  // -- 1 Rules Trading Platform Texts
  static const String terms = "1. Terms";
  static const String termsRules = " In these rules, unless the context otherwise requires, the following terms have the following meanings:\n";
  static const String tradingPlatform = " - the website https://www.easyshoppin.ru and the Easy Shoppin mobile application, which are a service that provides access to information about products intended for potential Buyers (consumers).";
  static const String ownerPlatform = " - of the Trading Platform is Easy Shoppin LLC (according to the text of these Rules - Easy Shoppin (Legal address: 142181 Ulyanovsk region, building 1, OGRN 1067746062449, Email: sale@easyshoppin.ru).";
  static const String userTradingPlatform = " - any individual using the Trading Platform under the terms of these Rules.";
  static const String sellerTradingPlatform = " is an individual entrepreneur, legal entity or self-employed citizen, duly registered in Russian or foreign jurisdiction, engaged in the sale of goods and offering the Buyer to enter into a purchase and sale agreement for the Goods by placing the Goods on the Marketplace.";
  static const String bayerTradingPlatform = " - an individual who purchases Goods on the Marketplace for personal and/or household needs not related to business activities, by placing and paying for an Order through the payment services of the Marketplace.";
  static const String goodsTradingPlatform = " - are the subject of a purchase and sale agreement concluded between the Buyer and the Seller. The Seller is the owner of the Goods being sold. All relationships related to the purchase and sale of Goods arise between the Seller, who places the Goods on the Marketplace, and the Buyer.";
  static const String personalAccountPlatform = " - is a personal section of the Trading Platform that is not accessible to third parties, created by the Buyer and used for the purpose of placing Orders and processing Services, as well as receiving special offers in accordance with these Rules, which is accessed after registration by entering the Buyer’s authentication data.";
  static const String orderPickUpPlatform = " - point is a unit of the logistics infrastructure that issues Orders to Buyers who have indicated the address of the corresponding Order pick-up point as the delivery location.";
  static const String postamat = " - is an automated terminal for issuing goods.";
  static const String orderBayer = " - the implementation by the Buyer of actions aimed at concluding an agreement for the provision of delivery services for the Goods, as well as an agreement/sales agreements for the corresponding Goods/Goods with Easy Shoppin  and/or other Seller/Sellers, by registering the specified services and Goods on the Marketplace.";
  static const String servicesDelivery = " - delivery services provided by Easy Shoppin to the Buyer in relation to Goods purchased by the Buyer from Easy Shoppin or other Sellers on the Marketplace or returned by the Buyer to Easy Shoppin  or the Seller.";
  static const String deliveryGoods = " - delivery of goods to the address specified by the Buyer, different from the addresses of Order Pickup Points and Post Office addresses.";
  static const String promotionLoyalty = "- is a loyalty program conducted by Easy Shoppin, which includes special conditions for ordering certain Products.";
  static const String promotionalDiscount = "- is a discount that is provided on a specific Product. The discount amount is indicated on the Product page. The price of the Product is indicated taking into account the promotional discount. The price difference between a product without a discount and a product with a discount is the benefit of the final Buyer within the framework of the action to purchase a specific specified product.";
  static const String discountPromotionalCode = "- discount using a is a discount that is provided for a specific group of Products when the Buyer places an Order. The price difference between a product without a discount and a product with a discount is the advantage of the final Buyer within the framework of the action to purchase a specific specified product";
  static const String promotional = "- code is a special code that provides a discount on a specific group of Products and has an expiration date. Promo codes are applied automatically. Only one promotional code can be applied to one item of goods. The price difference between a product without a discount and a product with a discount is the benefit of the final Buyer within the framework of the action to purchase a specific specified product.";
  static const String esDiscount = "- is a discount provided to the Buyer under certain conditions established by the Marketplace.";
  static const String balance = "- the amount of available funds at the buyer’s disposal, which he can dispose of at his own discretion by transferring them to the bank details specified by the Buyer or by paying for subsequent orders on the Trading Platform website in the amount of up to 100% of the cost of the goods. When canceling/returning an order paid using “Balance”, the funds are returned back to “Balance”.";
  static const String returnGoods = "- refusal by the Buyer of the Goods of proper quality in order to return them to Easy Shoppin or the Seller of the goods.";
  static const String chat = "- is a service of the Marketplace for interaction between the Buyer and Easy Shoppin and/or the Seller.";
  static const String productCard = "- information about the product, containing a visual and text description of the product, its main characteristics, information about the seller of the product, its price, as well as other information, the indication of which is necessary to make a decision about ordering the product. The product card contains the essential terms of the purchase and sale agreement and is filled out by the Seller of the goods independently.";
  static const String registrationData = "Registration data - data that is indicated (contained) in the Personal Account after registration and data specified by the User when placing an order.";
  static const String esElectronicWallet = "- is an electronic means of payment provided to the Buyer by Easy Shoppin Bank LLC on the basis of an agreement concluded between Easy Shoppin Bank LLC and the Buyer.";

  // -- 2 Rules Trading Platform Generation Provision Texts
  static const String generationProvisions = "2. General provisions";
  static const String tradingPlatformSearch = " The trading platform provides the Buyer with a free opportunity to search for information about the Products, familiarize yourself with the product offerings of Easy Shoppin  and other Sellers, receive (including based on search results) product offers and information, order Products, select a delivery method, pay for Products, as well as other functional possibilities.";
  static const String usingTradingPlatform = " By using the Trading Platform, placing Orders, paying for Orders, refusing Goods, the Buyer unconditionally agrees to the terms of these Rules, which are a Public Offer within the meaning of Art. 437 of the Civil Code of the Russian Federation, as well as with the terms of the Rules for the Application of Recommendation Technologies, and undertakes to comply with them.";
  static const String sellersMarketplace = " Sellers on the Marketplace include both Easy Shoppin and other legal entities of various organizational and legal forms, individual entrepreneurs, citizens using the special tax regime “Professional Income Tax”, including also foreign citizens and legal entities.";
  static const String infoSellerProduct = " Information about the Seller of the Product is placed in the Product Card on the Marketplace under the “i” icon (or by hovering over the icon). This information is provided directly by the Seller of the goods and is published by Easy Shoppin  without changing its content or meaning. Responsibility for the completeness of the information and its accuracy lies with the Seller providing the information.";
  static const String cardGoodsOffered = " A card of goods offered for sale by a foreign seller may not contain information about the identification number due to the difference in formats and the absence of such numbers in foreign jurisdictions. If necessary, information allowing the identification of such a Seller will be provided at the consumer's request by the Seller itself or Easy Shoppin  (if Easy Shoppin  has such information).";
  static const String reviewRatingsMarketplace = " The Marketplace has implemented a service for reviews and ratings of Buyers for purchased Products, which operates according to the following rules, with which the Buyer who leaves a review of the Product and evaluates the Product agrees:";
  static const String authorizedBuyer= " Any authorized Buyer can leave reviews about Products posted on the Marketplace and rate Products when using the Marketplace;";
  static const String buyersReview = " With the Buyer’s review, his name indicated in the Personal Account of the Trading Platform will be published in the appropriate section of the Trading Platform;";
  static const String noReviewMarketplace = " Reviews, the content of which is not related to the work of the Marketplace or making purchases on it, are not published;";
  static const String noReviewActualExperience = " Reviews, the content of which does not relate to the actual experience of using the relevant Product, are not published;";
  static const String noReviewProfanity = " Reviews that contain profanity, offensive statements, including photographs and images that are unacceptable for publication from an ethical point of view, are not published;";
  static const String noReviewOtherWebsites = " Reviews and comments containing links to other websites, personal data of third parties, as well as other information prohibited or restricted for distribution, are not published;";
  static const String publishedReviewDeleted = " A published review may be deleted at any time without explanation;";
  static const String reviewConsideredRelevant = " Easy Shoppin independently determines the period during which reviews are considered relevant and for which they are published.";
  static const String buyerAgreesMessages = " The Buyer agrees that messages and materials posted by him on the Marketplace may be used by Easy Shoppin, including in other Easy Shoppin services and applications, in advertising or marketing materials posted on Easy Shoppin resources on the Internet, as well as on other resources and sites on the Internet, to attract the attention of other consumers to the Marketplace as a whole or to the goods and services of third parties, as with the indication of the author of the message or material (the name of the author will be indicated as the name of the Buyer, which he indicated during registration or in the settings of his data in the Personal Account), and without it, without the obligation to provide reports on the use of such messages and materials, without the need to obtain special permission from the Buyer and without paying royalties, throughout the world without a time limit, with the right of Easy Shoppin to provide the specified rights to use such messages and materials to third parties.";
  static const String buyerAgreesReview = " The Buyer agrees that the reviews and ratings he left may be published and used by Easy Shoppin on the Marketplace or on third party websites without additional consent from the Buyer. In this case, reviews and images attached to them are published and used “as is”, preserving the author’s grammar and punctuation, under the Buyer’s name indicated in the Personal Account. The buyer is responsible for the accuracy of the information contained in the reviews he left.";
  static const String buyerInformedTrading = " The Buyer is informed that the Trading Platform, which collectively represents computer programs, as well as the generated graphic and audiovisual displays, the user interface as a whole, design elements, text, graphic images and other information posted by Easy Shoppin, are protected results of intellectual activity, the exclusive right to which belongs to Easy Shoppin.";
  static const String providesUsers = " Easy Shoppin provides Users with a non-exclusive license to use databases and computer programs necessary for using the Trading Platform for the purposes provided for in this Offer free of charge.";
  static const String licenseGranted = " A non-exclusive license is granted from the moment of access to the Marketplace and continues to be valid as long as the User uses the Marketplace for personal, non-commercial purposes. Searching and viewing offers on the Marketplace is available to all users, regardless of registration and authorization. In order to gain access to other functionality of the Marketplace, namely: make a purchase, place an order, you need to register a Personal Account.";
  static const String registrationTradingPlatform = " From the moment of registration on the Trading Platform, Easy Shoppin provides the User (the owner of the personal account) for the entire term of the Agreement with a non-exclusive, non-transferable license to use the Trading Platform in the part directly related to the User, namely, the right to use the functionality of the Trading Platform solely for the purpose of exercising the rights and obligations in within the framework of this Offer, including: for registration and identification on the Marketplace, for interaction with support specialists for users/customers on the Portal, with sellers, including, but not limited to, for the purpose of receiving services provided for in the Agreement, transfer and return of Goods, to request and receive information in the manner and under the conditions provided for in the Agreement.";
  static const String userBuyer = " The user/buyer is not entitled to:";
  static const String useTradingPlatform = "1. use the Trading Platform, its individual elements in ways and/or for purposes not provided for in this Offer;";
  static const String sourceCodeTradingPlatform = "2. carry out any actions related to modification of the source code of the Trading Platform;";
  static const String registeringPersonalAccount = " By registering in your personal account/using the Trading Platform, the User fully and unconditionally agrees to the terms of use of the Trading Platform, as well as other intellectual property of Easy Shoppin. In case of violation by the User of the terms of use of the Trading Platform and/or other intellectual property of Easy Shoppin, including, but not limited to, means of individualization of Easy Shoppin, Easy Shoppin has the right to demand payment by the User of a penalty (fine) in accordance with the Agreement, and also reserves the right to block the User’s personal account at the market.";
  static const String ongoingPromotion = " Easy Shoppin has the right, as part of the ongoing promotion, to determine individual Products, upon leaving reviews for which the Buyer can be awarded Bonus Points. Bonus points are accrued under the following conditions:";
  static const String productsParticipatePromotion = " Bonus points are awarded only for reviews of Products that participate in the promotion, which is reflected in the Product Card.";
  static const String productParticipatingBuyer = " A review of a Product participating in the promotion can be left by the Buyer who purchased this Product no later than 5 (five) days after the Buyer receives this Product.";
  static const String numberBonusPoints = " The number of Bonus Points awarded for a review depends on the availability of a text description, video and photographs of the Product and is reflected in the review registration interface on the Marketplace.";
  static const String reviewChecked = " Each review is checked for compliance with the conditions of clause 2.4 of these Rules and is published on the Marketplace, subject to approval based on the results of the check. Bonus points are awarded to the Buyer for a published review 14 days after its publication.";
  static const String bonusPointsAwarded = " Bonus points will not be awarded if the review has not passed the compliance check and is therefore not published.";
  static const String bonusPointsBuyer = " Bonus points are not awarded if the Buyer, after writing a review, returns the product in the manner prescribed by these Rules. A review left for such a Product, if it complies with the conditions of clause 2.4 of these Rules, may be published on the Marketplace.";
  static const String bonusPointsGoods = " Bonus points can be used to pay for orders of Goods on the Marketplace and cannot be transferred to an account with a credit institution in the manner provided for in clause 5.17 of these Rules. When paying for an order, 1 bonus point is equal to 1 Russian ruble.";
  static const String publishingReview= " If, after publishing a review, it is determined that the review does not comply with the conditions specified in clause 2.4 of these Rules, Easy Shoppin reserves the right to delete it with a subsequent reduction in the Personal Account Balance of the Buyer who left the review by the amount of previously accrued Bonus Points.";

  // -- 3 Registration Texts
  static const String registrationSite = "3. Registration on the site";
  static const String onlyRegisteredBuyers = " Only registered Buyers can place an Order on the Marketplace, and the Buyer has the right to register on the site only 1 (one) time, i.e. can have only one Personal Account. Having two personal accounts with the same registration data is not allowed.";
  static const String registeringMarketplace = " When registering on the Marketplace, as well as during its further use, the Buyer provides Easy Shoppin with his registration data (including personal data): telephone number, delivery address, details of electronic means of payment (number, expiration date, CVV/CVC code).";
  static const String buyerDiscretion = " The Buyer has the right, at his discretion, to provide Easy Shoppin with additional registration data (including personal data), namely: full name, gender, date of birth, information about body measurements (clothing size), as well as other information that the Buyer deems it possible to provide.";
  static const String accessPersonalAccount = " To gain access to the Personal Account, a buyer who has registered on the Marketplace undergoes individual identification by entering an access code sent by Easy Shoppin to the contact phone number specified in the Personal Account via SMS message or push notification. Individual identification of the Buyer allows you to avoid unauthorized actions by third parties on behalf of the Buyer and provides access to additional services.";
  static const String accessCodeBuyer = " Transfer of the access code by the Buyer to third parties is not permitted. The Buyer is responsible for all possible negative consequences, including material losses, in the event of transferring the access code, Personal Account credentials, as well as providing access to the Personal Account to third parties.";
  static const String changingPhoneNumber = " Changing the phone number in your Personal Account cannot be done for technical reasons.";
  static const String lossTelephoneNumber = " The loss of the telephone number for which the Personal Account is registered, as well as its transfer to another person, is the responsibility of the Buyer. The buyer is responsible for all possible negative consequences, including material losses.";
  static const String registrationDataVoluntarily = " Registration data (including personal data) is provided by him voluntarily. In the case of using data from third parties, the specified data is indicated with the informed and prior and confirmed consent of these persons;";
  static const String registrationDataElectronically = " Registration data (including personal data) is transmitted electronically via open communication channels of the Internet, used (processed, collected, systematized, stored and processed in other ways) by Easy Shoppin to implement the purposes specified in these Rules and for the same purposes may be transferred to third parties;";
  static const String registrationDataPolicy = " Registration data (including personal data) may be processed by Easy Shoppin for the purpose of promoting goods and services by making direct contacts with the Buyer using communication channels in accordance with the Policy regarding the processing of personal data;";
  static const String registrationDatInternet = " Registration data (including personal data) is processed by Easy Shoppin for the purpose of sending advertising and information to the Buyer via telecommunication networks, including via the Internet, in accordance with Article 18 of the Federal Law of June 13, 2006 No. 38-FZ “On Advertising”;";
  static const String registrationDataProtection = " Registration data (including personal data) specified by the Buyer, for the purpose of additional protection against fraudulent activities, may be transferred to the credit institution that carries out transactions for payment of Orders placed on the Marketplace, as well as to other third parties ensuring the security of Easy Shoppin;";
  static const String registrationDataEmail = " The consent given by the Buyer to the processing of his registration data (including personal data) is unlimited and can be revoked by the Buyer or his legal representative by submitting a written application sent to the email address: sales@easyshoppin.ru.";
  static const String buyerInformed = " The Buyer is informed and agrees that Easy Shoppin collects, records, systematizes, accumulates, stores, refines (updates, changes), extracts, analyzes and uses, transfers (distributes, provides, access), entrusts processing to third parties, receives from third parties persons, depersonalization, blocking, deletion, destruction of the Buyer’s registration data (including personal data).";
  static const String bankCard = " The buyer is informed and agrees that hiding a bank card in the Personal Account does not mean withdrawing consent to the processing of this part of personal data. Consent to the processing of personal bank card data may be withdrawn by the Buyer by notification sent to the email address: sales@easyshoppin.ru.";
  static const String copyingApp = " By copying the Easy Shoppin Mobile Application and installing it on his mobile device, the User expresses his full and unconditional agreement with all the terms of this Offer.";
  static const String correctnessInformation = " Easy Shoppin is not responsible for the accuracy and correctness of the information provided by the Buyer during registration, as well as for possible negative consequences caused by the Buyer providing inaccurate or incorrect information about himself.";

  // -- 4 Placing an order Texts
  static const String placingOrder = "4. Placing an order";
  static const String purchaseTermsRules = " The purchase and sale agreement is considered concluded under the terms of these Rules and entails legal consequences for the Seller, Easy Shoppin and the Buyer only when ordering the Product and paying for it through the use of the services of the Marketplace, as a result of which information about the order is reflected in the Buyer’s Personal Account.";
  static const String concludingAgreements = " Concluding agreements with any third parties outside of software methods on the website or mobile application of the Trading Platform, as well as paying for an order in a way other than payment using special software on the website or mobile application of the Trading Platform (including, but not limited to, payment in cash to a third person, transfer of funds to bank details, payment of bills, invoices, invoice agreements and other primary documents received from third parties) does not give rise to legal consequences for Easy Shoppin, as for the owner of the Trading Platform, incl. upon receiving an offer to conclude such an agreement from information about goods posted on the website or mobile application of the Trading Platform.";
  static const String placingOrderPersonalAccount = " When placing an order using the Personal Account, responsibility for the Order, including possible financial losses, lies with the Buyer - the owner of the Personal Account.";
  static const String orderingGoods = " By ordering Goods on the Marketplace, the Buyer enters into a purchase and sale agreement with the Seller of the Goods, as well as an agreement for the provision of delivery services for Goods with Easy Shoppin. Within the framework of one Order, the Buyer may enter into an agreement for the provision of delivery services for the Goods of several Sellers, with the simultaneous conclusion of several purchase and sale agreements in relation to the Goods selected by the Buyer.";
  static const String orderingProduct = " When ordering a Product, the Seller of which is any seller, with the exception of Easy Shoppin, the Buyer, within the framework of the purchase and sale agreement, enters into a contractual relationship directly with the Seller selling this Product.";
  static const String clickingButtonPlacePay = " By clicking the “place”/“pay” button (or another button that confirms the Buyer’s will to complete the Order and transfer payment for it), the Buyer confirms familiarization with these Rules and full agreement with all the terms of these Rules: including the conditions for the processing of personal data , payment for goods, conditions and procedure for delivery of the Goods both to the Buyer and from the Buyer, conditions for returning goods and filing claims.";
  static const String informationProductCard = " The information presented in the Product Card cannot fully convey all the characteristics of the product (including color, shape, availability and description of some functions). To obtain complete information, the Buyer must contact the Seller. The Buyer’s placing an Order without such a request is a confirmation that the information about the Product was complete, understandable and sufficient for placing the Order.";
  static const String placingOrderBuyer = " By placing an Order, the Buyer agrees that Easy Shoppin may entrust the execution of the contract to a third party, remaining responsible for its execution to the Buyer.";
  static const String placingOrderMarketplace = " By placing an order on the Marketplace, the Buyer agrees to receive:";
  static const String emailsPushNotifications = " Emails/push notifications that Easy Shoppin may send to the Buyer;";
  static const String messagesSMS = " Messages (SMS) to the phone number specified by the Buyer;";
  static const String callTelephoneNumber = " A call with an offer to evaluate the quality of the Trading Platform to the telephone number specified by the Buyer.";
  static const String buyerPersonalAccount = "The Buyer has the right to refuse these methods of interaction by disabling them in the Personal Account.";
  static const String orderCountryEAEU = " By placing an Order in a country that is a member of the Eurasian Economic Union (hereinafter referred to as the “EAEU”), in relation to Goods that are delivered from a country that is not a member of the EAEU and is subject to customs clearance when imported into the EAEU, the Buyer confirms that he is duly informed and agrees with the following:";
  static const String importEAEU = " The norm for duty-free import of Goods into the territory of the EAEU is determined by the regulations of the EAEU (as of February 1, 2024, it was 1000 Euros).";
  static const String obligationDuties = " If the cost of the Goods exceeds the duty-free import rate, the obligation to pay customs duties lies with the Buyer; Easy Shoppin is not responsible for customs duties.";
  static const String customsClearanceGoods = " For customs clearance of the Goods, the Buyer may be required to provide additional data, including personal data, to the customs representative.";
  static const String availableCustomsRepresentatives = " The list of available customs representatives is determined by Easy Shoppin at its discretion. The buyer enters into an agreement with such a customs representative in the manner specified in these Rules.";
  static const String returnGoodsCarried = " Return of goods is carried out in accordance with Section 7 of the Rules.";
  static const String orderGoodsUnitrade = " In the case of placing an order for Goods that are subject to customs clearance when imported into Russia, the Buyer confirms his acceptance of the offer agreement for the provision of services to him by a customs representative of Unitrade JSC, published at http://sms.unitrade.su/, and also gives your consent to the transfer and processing of your personal data to the partners of Easy Shoppin LLC for the purpose of organizing customs clearance of your orders.";
  static const String orderGoodsTANAIS = " In the case of placing an order for Goods that are subject to customs clearance when imported into Russia, the Buyer confirms his acceptance of the offer agreement for the provision of the services of a customs representative of TANAIS JSC (121596, Moscow, internal ter.g. municipal district Mozhaisky, st. . Gorbunova, 2, building 3, floor/room 6/II, room 36, INN: 7730642532, OGRN: 1117746295314), published at https://tanais.express/pages/offerta/ also gives his consent to the transfer and processing of his personal data to the partners of Easy Shoppin LLC for the purpose of organizing customs clearance of his orders.";
  static const String orderGoodsJSC = " By paying for the Goods sent by international mail, the Buyer enters into an Offer Agreement with Russian Post JSC (you can also read the text of the Offer Agreement at https://customs.pochta.ru/oferta), which is an authorized operator for the purposes of declaring goods sent in international mail and paying customs duties in relation to such goods. Easy Shoppin does not bear any responsibility for the Buyer’s fulfillment of obligations to pay customs duties and declare goods, as well as for the fulfillment by the authorized operator (as indicated above) of its obligations to the Buyer in accordance with the Offer Agreement. In accordance with these provisions, the Buyer grants Easy Shoppin the right to transfer to the authorized operator information about the number and date of the Order, as well as the amount of payments payable in accordance with the requirements of the legislation of Russia and the Eurasian Economic Union in connection with the declaration of goods and payment of customs duties. Easy Shoppin is not responsible for the processing of the Buyer's payment, as well as the processing of data provided by the Buyer to the authorized operator and does not participate in these operations in any way.";
  static const String orderGoodsGBSBroker  = " In the case of placing an order for Goods that are subject to customs clearance when imported into Russia, the Buyer confirms his acceptance of the offer agreement for the provision of the services of a customs representative of GBS-broker LLC (105066, Moscow, Olkhovskaya St., 16, building 5- 5A, basement room 1 room 15, TIN: 9701083788, OGRN: 1177746840787), published at https://www.gbs-broker.ru/docs/customs_repr_03032023.docx, and also gives his consent to the transfer and processing of his personal data partners of Easy Shoppin LLC for the purpose of organizing customs clearance of their orders.";
  static const String orderGoodsLOGISTIC = " In the case of placing an order for Goods that are subject to customs clearance when imported into Russia, the Buyer confirms his acceptance of the offer agreement for the provision of the services of a customs representative of SEL LOGISTIC LLC (690025, Vladivostok, Fanzavod St., 1, building 2, premises 1, INN: 2725106960, OGRN: 1112722010026), published at https://cellog.ru/oferta, and also gives his consent to the transfer and processing of his personal data to the partners of Easy Shoppin LLC for the purpose of organizing customs clearance of their orders.";

  // -- 5 Payment for the order Texts
    static const String paymentOrder = "5 Payment for the order";
    static const String returnGoodsCarriedAccordance = "5.1 The price of the goods is indicated in the Product Card in rubles of the Russian Federation and includes value added tax.";
    static const String priceGoodsIndicated = "5.2 Prices for the Products are determined by the Sellers and are indicated in the Product Card. The cost of delivery services is determined by Easy Shoppin unilaterally and indisputably and is indicated on the Marketplace. Payment for the Order means the Buyer’s agreement with the price of the Product and the cost of delivery.";
    static const String pricesProductsDetermined = "5.3 The final Price of the Product is determined by the sequential effect of discounts on the Price of the Product in the following order:";
    static const String finalPriceProduct = "5.3.1. Promotional discount;";
    static const String promotionalDiscountPayment = "5.3.2. Discount using Promo Code;";
    static const String discountPromoCode = "5.3.3. WB Discount.";
    static const String esDiscountPayment = "5.4 You can take advantage of the WB Discount only by placing orders in your Personal Account and logging into the Marketplace using your credentials. WB The discount is tied to your Personal Account and is calculated based on purchases made through it. In case of re-registration on the site, purchase history and WB Discount are not transferred from the old Personal Account to the new Personal Account. Order statistics in the new Personal Account are kept from scratch.";
    static const String onlyPlacingOrders = "5.5. Payment for an order in a manner other than payment using special software on the website or mobile application of the Trading Platform (including, but not limited to, payment in cash to a third party, transfer of funds to bank details, payment of bills, invoices, contracts - invoices and other primary documents received from third parties) does not give rise to legal consequences for Easy Shoppin as the owner of the Trading Platform, incl. upon receiving an offer to conclude such an agreement from information about goods posted on the website or mobile application of the Trading Platform.";
    static const String paymentOrderManner = "5.6 The Buyer may have access to advance payment for the Order, as well as payment for the Order upon receipt. The choice of payment method belongs to the Buyer. Easy Shoppin may unilaterally limit the choice of payment method by establishing prepayment for the Order.";
    static const String accessAdvancePayment = "5.7 The trading platform does not use cash payments in its activities.";
    static const String buyersPreviouslyPurchased = " Buyers who previously purchased goods in cash and who have returned or intend to return the goods on legal grounds have the right to demand a refund to the account specified by the Buyer with a credit institution.";
    static const String tradingPlatformPayments = "5.8 The Buyer placing an Order on the Marketplace is given the opportunity to choose a payment option in accordance with the methods provided by the Marketplace:";
    static const String paymentUsingBankCard = "5.8.1. Payment using a bank card;";
    static const String personalAccountBalance = "5.8.2. Payment from the Personal Account Balance;";
    static const String paymentInstallments = "5.8.3. Payment by installments;";
    static const String fastPaymentSystem = "5.8.4. Payment through the Fast Payment System (FPS);";
    static const String creditPaymentInstallments = "5.8.5. Payment using credit funds. Payment in installments;";
    static const String paymentElectronicWallet = "5.8.6. Payment using ES Electronic Wallet;";
    static const String otherPaymentMethods = "5.8.7. Other payment methods introduced into the Marketplace.";
    static const String paymentUponReceipt = "5.9. Payment upon receipt using a bank card";
    static const String paymentMethodUpon = "5.9.1 When choosing a payment method upon receipt using a bank card or other available services that allow payment for orders placed on the Marketplace using the specified method, the Buyer sends Easy Shoppin an order to make a payment from the account, providing consent to the processing of payment personal data.";
    static const String absenceDebitingFunds = "5.9.2. In the absence of debiting funds from the Buyer's account in favor of the Trading Platform in the amount of the cost of the order or part thereof, or cancellation of payment due to a technical failure and (or) other unforeseen error, the Buyer agrees that Easy Shoppin, on the basis of the previously given order of the Buyer in order to ensure the execution of the purchase and sale agreement and to prevent the formation of debt, it has the right, based on available payment personal data, consent to the processing of which has not been revoked, to initiate actions aimed at the Buyer fulfilling payment for the order without additional notice.";
    static const String buyerUnderstandsAbove = "5.9.3. The Buyer understands that the above actions on the part of the Owner of the Trading Platform are carried out in the interests of the Buyer and are aimed at implementing the will of the Buyer as a party to this agreement.";
    static const String sendingOrderAgreeing = "5.9.4. The buyer, sending an order and agreeing to write off funds, incl. debt incurred by the Owner of the Trading Platform, understands and agrees that the processing of personal data hidden by him (data on means of payment) by the Owner of the Trading Platform continues for the purposes reflected in these Rules and provided for by the current legislation on the protection of personal data. Hiding a bank card from your Personal Account in accordance with clause 3.9 of the Rules does not constitute a withdrawal of consent to the processing of such personal data.";
    static const String paymentPersonalAccountBalance = "5.10. Payment from Personal Account Balance";
    static const String orderPersonalAccountBalance = "5.10.1 When choosing to pay for the Order from the Personal Account Balance, the price of the Product and the cost of the delivery service are debited from the Personal Account Balance. If Advances and Return Payments are simultaneously taken into account in the Personal Account Balance, when paying for goods, the amounts of Return Payments are taken into account first.";
    static const String insufficientFundsReflected = "5.10.2. If there are insufficient funds reflected in the Personal Account Balance, the unpaid balance of the price of the Product and the cost of the delivery service is debited from the bank card, the details of which are indicated in the Personal Account.";
    static const String paymentByInstallments = "5.11. Payment by installments";
    static const String paymentMethodInstallments = "5.11.1 When choosing the payment method in installments, the conclusion of an agreement between a banking or financial organization and the Buyer for payment for goods and (or) services occurs on the terms of this organization.";
    static const String choosingInstallmentPayment = "5.11.2. When choosing an installment payment method on the Marketplace website, the Buyer is given a discount on the product, which is equal to the cost of services of a banking or financial organization in connection with the purchase of the product in installments, and covers the cost of these services. Thus, the amount payable to such organization does not exceed the original cost of the goods, provided that additional services of such organization are not purchased.";
    static const String buyerAssumesObligations = "5.11.3. The Buyer assumes all obligations and risks associated with concluding an agreement to provide installment plans and/or credit funds to pay for goods and (or) services on the Marketplace. Neither the Owner of the Marketplace nor any other Seller takes part in the consideration by a banking or financial institution of the possibility of providing installment plans and/or credit funds to the Buyer and are not responsible in case of refusal to the Buyer in such payment, and are not responsible for the actions of the Buyer regarding transactions and acquisitions other services provided by a banking or financial organization to which they are not a party.";
    static const String paymentUsingCreditFunds = "5.12. Payment using credit funds. Payment in installments";
    static const String paymentInInstallments = "5.12.1 Payment in installments from Easy Shoppin. When choosing the “Payment in installments” payment method for Goods on the Trading Platform website, the Buyer agrees to the terms of the contract set forth in the Agreement on concluding contracts with the payment term “Payment in installments,” which are an integral part of these Rules. When choosing the “Payment in installments” payment method for the Goods, the terms of the Agreement on concluding contracts with the payment term “Payment in installments” regarding payment for the Order and refund of funds for the Goods have priority.";
    static const String paymentMethodGoods = "5.12.2. Payment in installments from Easy Shoppin partners";
    static const String buyerChoosesPayment = "When the Buyer chooses a payment method in installments from Easy Shoppin partners, the conclusion of an agreement between a banking or financial organization and the Buyer for payment for Goods and (or) services occurs on the terms of this organization.";
    static const String buyerAssumesObligationsRisks = "The Buyer assumes all obligations and risks associated with concluding an agreement with a banking or financial organization for payment for Goods and/or services on the Marketplace. Neither Easy Shoppin nor any other Seller takes part in the consideration by a banking or financial organization of the possibility of providing funds to the Buyer and are not responsible in the event of the Buyer’s refusal to make such payment, and are also not responsible for the Buyer’s actions in transactions and the purchase of other services of the banking or financial organization, which they are not a party to.";
    static const String paymentUsingElectronicWallet = "5.13. Payment using WB Electronic Wallet";
    static const String orderUsingElectronicWallet = "When choosing to pay for the Order using the WB Electronic Wallet, the cost of the Product and the cost of the delivery service are debited from the WB Electronic Wallet. If there are insufficient funds on the balance of the WB Electronic Wallet, the unpaid balance of the cost of the Order and the cost of the delivery service is debited from the bank card, the details of which are indicated in the Personal Account.";
    static const String orderingServices = "5.14. By purchasing a product or ordering services on the Marketplace, the Buyer provides Easy Shoppin with consent to write off funds using the bank card details provided by the Buyer when placing an order for the product or the details of which are specified by the Buyer in the Personal Account (hereinafter referred to as Payment Data), consent to the processing of which has not been revoked in accordance with the established procedure, in the manner and cases provided for in this paragraph.";
    static const String reasonFundsGoods = "5.14.1. If for some reason the funds for goods or services were not written off immediately after placing the Order (receipt of the Order), Easy Shoppin has the right, on its own initiative, to write off funds for all submitted Payment Data in accordance with the rules of payment systems, including VISA, MasterCard, MIR, Fast Payment System, and on the following conditions:";
    static const String reasonFundsGoods1 = "1. the write-off amount is the unpaid cost of goods or services, which the Buyer was familiar with at the time of placing the order or before that moment;";
    static const String reasonFundsGoods2 = "2. write-off is made in Russian Rubles, unless another currency was agreed upon by the parties when placing the order;";
    static const String reasonFundsGoods3 = "3. Easy Shoppin does not charge the Buyer a commission or other fee for such write-offs;";
    static const String reasonFundsGoods4 = "4. Cancellation of transactions and refund of funds are carried out according to the rules of the payment system, in accordance with which the debit is carried out.";
    static const String paragraphRevoked = "5.14.2. The consent given in accordance with this paragraph may be revoked by the Buyer by deleting the Payment Data from the Personal Account.";
    static const String uponReceiptOrder = "5.15. Upon receipt of an Order with the selected payment method upon receipt, payment for the cost of the Order can be received by Easy Shoppin in any method available for selection when placing an order, regardless of the payment method for the Order selected by the Buyer. The Buyer understands that the above actions on the part of the Owner of the Trading Platform are carried out in the interests of the Buyer and are aimed at implementing the will of the Buyer as a party to this agreement.";
    static const String purchaseSaleAgreement = "5.16. If the purchase and sale agreement for a Product presented on the Marketplace is concluded not with Easy Shoppin, but with another Seller who has placed an offer for the Product on the Marketplace, payment is made to the account of Easy Shoppin, acting on behalf of the relevant Seller in terms of accepting funds in payment account for Goods with the involvement of an authorized payment acceptance operator or electronic money operator and is the recipient of the payment as a representative of the Seller.";
    static const String accordanceTermsRules = "5.17. In accordance with the terms of these Rules, a cash receipt in electronic form is provided by telephone number by displaying information in the form of a message in the Personal Account. The cash receipt in electronic form is sent to the “Electronic Receipts” section of your Personal Account. The buyer can provide an email address in the “Profile” section and independently send a cash receipt to the email address in the “Electronic Receipts” section.";
    static const String buyerInitiateTransfer = "5.18. The Buyer has the right at any time to initiate the transfer of funds recorded and displayed on the Personal Account Balance to an account with a credit institution in full or in part, with the exception of Bonus Points accrued in accordance with clause 2.10 of these Rules. Easy Shoppin transfers the funds accounted for and displayed on the Balance within 10 days from the date of receipt of the Buyer’s order. The Buyer’s order is sent using the “Withdrawal of Funds” functionality in the “Balance and Transaction History” section of the Personal Account.";
    static const String buyerAcknowledges = "5.19. The Buyer acknowledges that payment methods, as a result of which Easy Shoppin does not receive information from which account the payment was made by the Buyer, include payment for the Goods using the Faster Payment System (FPS).";

    // -- 6 Order delivery Texts
    // static const String orderDelivery = "6. Order delivery";
    // static const String orderDelivery = "6.1 Delivery of the Goods to the Buyer is carried out to the place specified by the Buyer. As the place of delivery, the Buyer can indicate the address of the Order Pickup Point, Post Office, or another address, in which case the Goods are delivered “to the door.”";
    // static const String orderDelivery = "6.2 Delivery of the Goods to the Buyer is carried out under the conditions set out in these Rules during the period of time automatically determined by the system when placing an order, and can be increased by agreement with the Consumer.";
    // static const String orderDelivery = "6.3 If the Buyer, after delivering the Goods to the place specified by the Buyer, does not receive the Order within the storage period specified in the Personal Account, Wildberry has the right to cancel the order without further informing the Buyer. When choosing the method of pre-payment for the Goods, the funds are returned to the Buyer within the period established by current legislation, with the exception of the costs of return transportation from the Buyer of the returned goods.";
    // static const String orderDelivery = "6.4 Delivery may be refused in the following cases:";
    // static const String orderDelivery = "6.4.1 In the absence of prepayment of the Goods, when such a requirement is mandatory for the Order.";
    // static const String orderDelivery = "6.4.2 In case of non-receipt of payment for the Goods after 10 minutes from the moment of placing the Order.";
    // static const String orderDelivery = "6.4.3 If there is no advance payment for the Goods for the selected “door-to-door” delivery method. In this case, the delivery method of this Product may be changed to delivery to the Order Pickup Point closest to the address specified by the Buyer when ordering door-to-door delivery.";
    // static const String orderDelivery = "6.5 Delivery of goods to the point of delivery of orders";
    // static const String orderDelivery = "6.5.1 Ordered items, with the exception of large-sized items, arrive in original packaging or a transparent bag.";
    // static const String orderDelivery = "6.5.2 All Products received at the order pick-up point are issued at a time, regardless of the date of registration and shelf life.";
    // static const String orderDelivery = "6.5.3 At the time of receiving the order, the Buyer, in the presence of an employee of the Order Delivery Point at the Order Delivery Point, without leaving the customer area and without entering the fitting room, is obliged to open the packaging of the goods and check the goods for integrity, absence of defects and correct attachment.";
    // static const String orderDelivery = "6.5.4 After opening the packaging and checking the Product in the presence of an employee of the Order Pickup Point, the Buyer has the right to try on the Product without a time limit.";
    // static const String orderDelivery = "6.5.5 Goods received at the Order Pickup Point are stored until a predetermined date specified in the Personal Account. The Buyer is considered to be notified of the storage period of the Goods at the moment the specified information is displayed in the Personal Account.";
    // static const String orderDelivery = "6.6 Door-to-door delivery";
    // static const String orderDelivery = "6.6.1 Ordered items, with the exception of large-sized items, arrive in original packaging or a transparent bag.";
    // static const String orderDelivery = "6.6.2 When choosing a payment method for the Goods upon receipt, the Goods are issued by a delivery service employee to the Buyer after full payment for the goods.";
    // static const String orderDelivery = "6.6.3 After full payment of the Order, the Buyer, in the presence of a delivery service employee, is obliged to open the packaging and check the Product, with the exception of large-sized goods, for integrity, absence of defects and correctness of the investment.";
    // static const String orderDelivery = "6.6.4 After opening the package and checking the goods in the presence of a delivery service employee, the Buyer has the right to try on the Goods in no more than 20 minutes.";
    // static const String orderDelivery = "6.7 Ownership of the Ordered Goods passes to the Buyer from the moment of actual transfer of the Goods to the Buyer after the latter has paid the full cost of the Goods and the delivery service for the Goods. The risk of accidental loss or damage to the Goods passes to the Buyer from the moment of actual transfer of the Goods to the Buyer, including upon receipt of the Goods, upon inspection and fitting before receipt of the Goods, as well as in other cases when the goods are actually received by the Buyer.";
    // static const String orderDelivery = "6.8 The Buyer is recommended to open the packaging of the goods in the presence of an employee of the Order Pickup Point or a delivery service employee and check the goods for integrity, absence of defects and correct attachment.";
    // static const String orderDelivery = "6.9 Delivery of large goods";
    // static const String orderDelivery = "6.9.1 Delivery of large-sized goods is carried out on general terms, with the exceptions specified in this paragraph of the Rules.";
    // static const String orderDelivery = "6.9.2 Delivery of large-sized goods is carried out by a third party who is not the Seller of the goods or a representative of Wildberries, and therefore, when delivering large-sized goods “to the door”, the Buyer inspects only the external condition of the consumer packaging of the Goods.";
    // static const String orderDelivery = "6.9.3 Inspection of large goods in the presence of a delivery service employee upon receipt is not available and is carried out by the Buyer independently after payment and receipt of the Goods.";
    // static const String orderDelivery = "6.10 Delivery of electronic devices, instruments and other technically complex goods";
    // static const String orderDelivery = "6.10.1 Electronic devices, instruments and other technically complex goods are available for order with advance payment of the cost of the goods and payment of the cost of the goods upon receipt, delivered either in the original packaging or in special packaging that prevents access to the goods without damaging it.";
    // static const String orderDelivery = "6.10.2 When ordering electronic devices, instruments and other technically complex goods with payment of the cost of the goods upon receipt, the Buyer, before receiving from an employee of the Order Pickup Point or a delivery service employee, agrees to write off the cost of electronic devices, devices and other technically complex goods. In case of successful write-off of the cost of electronic devices, instruments and other technically complex goods, an employee of the Order Pickup Point or a delivery service employee transfers the goods to the Buyer.";
    // static const String orderDelivery = "6.11 Delivery of Goods in the “Vehicles” category (hereinafter referred to as “Vehicles”) is carried out by the Sellers under the terms of Section 10 of the Rules.";

  // -- 7 Order cancellation and return Texts
  // static const String orderCancel = "7. Order cancellation and return";
  // static const String orderCancel = "7. Order cancellation and return";
  // static const String orderCancel = "7. Order cancellation and return";
  // static const String orderCancel = "7. Order cancellation and return";
  // static const String orderCancel = "7. Order cancellation and return";
  // static const String orderCancel = "7. Order cancellation and return";
  // static const String orderCancel = "7. Order cancellation and return";
  // static const String orderCancel = "7. Order cancellation and return";
  // static const String orderCancel = "7. Order cancellation and return";
  // static const String orderCancel = "7. Order cancellation and return";
  // static const String orderCancel = "7. Order cancellation and return";
  // static const String orderCancel = "7. Order cancellation and return";
  // static const String orderCancel = "7. Order cancellation and return";
  // static const String orderCancel = "7. Order cancellation and return";
  // static const String orderCancel = "7. Order cancellation and return";
  // static const String orderCancel = "7. Order cancellation and return";
  // static const String orderCancel = "7. Order cancellation and return";
  // static const String orderCancel = "7. Order cancellation and return";
  // static const String orderCancel = "7. Order cancellation and return";
  // static const String orderCancel = "7. Order cancellation and return";
  // static const String orderCancel = "7. Order cancellation and return";
  // static const String orderCancel = "7. Order cancellation and return";
  // static const String orderCancel = "7. Order cancellation and return";
  // static const String orderCancel = "7. Order cancellation and return";
  // static const String orderCancel = "7. Order cancellation and return";

  // -- 8 Rights, obligations and guarantees Texts

  // -- 9 Appeals and complaints Texts

  // -- 10 Rules for the sale of Vehicles Texts

  // -- 11 Other conditions Texts
}
