name: easyshoppin_eshop
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

#-------------------- PACKAGES --------------------#

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Utility Packages
  http: ^1.1.0
  intl: ^0.19.0
  logger: ^2.3.0
  lottie: ^3.1.2
  shimmer: ^3.0.0
  url_launcher: ^6.1.12
  connectivity_plus: ^5.0.2
  flutter_native_splash: ^2.3.2
  smooth_page_indicator: ^1.1.0
  audioplayers: ^6.0.0
  image_picker: ^1.1.2
  cached_network_image: ^3.3.1
  crypto: ^3.0.1
  geolocator: ^12.0.0
  location: ^7.0.0
  android_intent_plus: ^5.0.2
  yandex_mapkit: ^4.1.0
  permission_handler: ^11.3.1
  photo_manager: ^3.2.0
  dotted_border: ^2.1.0
  mailer: ^6.1.0
  shared_preferences: ^2.2.3
  flutter_config: ^2.0.2
  flutter_statusbarcolor_ns: ^0.5.0
  share_plus: ^9.0.0
  device_info_plus: ^10.1.0
  provider: ^6.1.2
  network_info_plus: ^5.0.3
  package_info_plus: ^8.0.0
  path_provider: ^2.1.3
  speech_to_text: ^6.6.0
  speech_to_text_google_dialog: ^0.0.6
  camera: ^0.11.0+1

  # Icons
  iconsax: ^0.0.8
  heroicons: ^0.10.0
  cupertino_icons: ^1.0.6
  bootstrap_icons: ^1.11.3
  material_symbols_icons: ^4.2762.0
  carbon_icons: ^0.0.1+2
  font_awesome_flutter: ^10.7.0
  ionicons: ^0.2.2
  remixicon: ^1.2.0
  mono_icons: ^1.0.0+2
  fluentui_system_icons: ^1.1.246
  solar_icons: ^0.0.5
  unicons: ^2.1.2
  eva_icons_flutter: ^3.1.0
  akar_icons_flutter: ^1.1.21
  typicons_flutter: ^0.5.0
  feather_icons: ^1.2.0
  mdi: ^5.0.0-nullsafety.0
  weather_icons: ^3.0.0
  tabler_icons: ^2.5.0+1

  # State Managment
  get: ^4.6.5
  get_storage: ^2.1.1

  # Product Specific
  readmore: ^3.0.0
  carousel_slider: ^4.2.1
  flutter_rating_bar: ^4.0.1

  # Firebase
  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  cloud_firestore: ^5.0.1
  google_sign_in: ^6.2.1
  firebase_storage: ^12.0.1
  firebase_messaging: ^15.0.1
  firebase_app_check: ^0.3.0+1

#-------------------- ./ PACKAGES END --------------------#

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Utility Packages
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1
  intl_translation: ^0.20.0
  intl_utils: ^2.8.7
  build_runner: ^2.1.7
  build_config: ^1.0.0

flutter_intl:
  enabled: true
  arb_dir: lib/localization/l10n
  output_dir: lib/generated/l10n

flutter:
  uses-material-design: true
  generate: true

  #-------------------- LOCAL ASSETS --------------------#
  assets:
  - assets/logos/
  - assets/icons/brands/
  - assets/images/content/
  - assets/images/banners/
  - assets/images/products/
  - assets/images/reviews/
  - assets/icons/categories/
  - assets/images/animations/
  - assets/icons/payment_methods/
  - assets/images/on_boarding_images/
  - assets/icons/flags/
  - assets/icons/other/
  - assets/sounds/
  - lib/localization/l10n/

  #-------------------- LOCAL FONTS --------------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800

flutter_icons:
  android: true
  ios: true
  image_path: assets/logos/easyshoppin-splash-logo-black.png
  