import 'package:flutter/material.dart';
import '../../../../../common/widgets/texts/rich_helper_text.dart';
import '../../../../../generated/l10n/l10n.dart';

class TGenerationProvision extends StatelessWidget {
  const TGenerationProvision({super.key});

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.all(8.0),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          buildRichTextSimple(context, '2.1.', S.of(context).tradingPlatformSearch),
          const SizedBox(height: 8.0),
          buildRichTextSimple(context, '2.2.', S.of(context).usingTradingPlatform),
          const SizedBox(height: 8.0),
          buildRichTextSimple(context, '2.3.', S.of(context).sellersMarketplace),
          const SizedBox(height: 8.0),
          buildRichTextSimple(context, '2.3.1.', S.of(context).infoSellerProduct),
          const SizedBox(height: 8.0),
          buildRichTextSimple(context, '2.3.2.', S.of(context).cardGoodsOffered),
          const SizedBox(height: 8.0),
          buildRichTextSimple(context, '2.4.', S.of(context).reviewRatingsMarketplace),
          const SizedBox(height: 8.0),
          buildRichTextSimple(context, '2.4.1.', S.of(context).authorizedBuyer),
          const SizedBox(height: 8.0),
          buildRichTextSimple(context, '2.4.2.', S.of(context).buyersReview),
          const SizedBox(height: 8.0),
          buildRichTextSimple(context, '2.4.3.', S.of(context).noReviewMarketplace),
          const SizedBox(height: 8.0),
          buildRichTextSimple(context, '2.4.4.', S.of(context).noReviewActualExperience),
          const SizedBox(height: 8.0),
          buildRichTextSimple(context, '2.4.5.', S.of(context).noReviewProfanity),
          const SizedBox(height: 8.0),
          buildRichTextSimple(context, '2.4.6.', S.of(context).noReviewOtherWebsites),
          const SizedBox(height: 8.0),
          buildRichTextSimple(context, '2.4.7.', S.of(context).publishedReviewDeleted),
          const SizedBox(height: 8.0),
          buildRichTextSimple(context, '2.4.8.', S.of(context).reviewConsideredRelevant),
          const SizedBox(height: 8.0),
          buildRichTextSimple(context, '2.5.', S.of(context).buyerAgreesMessages),
          const SizedBox(height: 8.0),
          buildRichTextSimple(context, '2.6.', S.of(context).buyerAgreesReview),
          const SizedBox(height: 8.0),
          buildRichTextSimple(context, '2.7.', S.of(context).buyerInformedTrading),
          const SizedBox(height: 8.0),
          buildRichTextSimple(context, '2.7.1.', S.of(context).providesUsers),
          const SizedBox(height: 8.0),
          buildRichTextSimple(context, '2.7.2.', S.of(context).licenseGranted),
          const SizedBox(height: 8.0),
          buildRichTextSimple(context, '2.7.3.', S.of(context).registrationTradingPlatform),
          const SizedBox(height: 8.0),
          buildRichTextSimple(context, '2.8.', S.of(context).userBuyer),
          const SizedBox(height: 8.0),
          buildRichTextSimple(context, '1.', S.of(context).useTradingPlatform),
          const SizedBox(height: 8.0),
          buildRichTextSimple(context, '2.', S.of(context).sourceCodeTradingPlatform),
          const SizedBox(height: 8.0),
          buildRichTextSimple(context, '2.9.', S.of(context).registeringPersonalAccount),
          const SizedBox(height: 8.0),
          buildRichTextSimple(context, '2.10.', S.of(context).ongoingPromotion),
          const SizedBox(height: 8.0),
          buildRichTextSimple(context, '2.10.1.', S.of(context).productsParticipatePromotion),
          const SizedBox(height: 8.0),
          buildRichTextSimple(context, '2.10.2.', S.of(context).productParticipatingBuyer),
          const SizedBox(height: 8.0),
          buildRichTextSimple(context, '2.10.3.', S.of(context).numberBonusPoints),
          const SizedBox(height: 8.0),
          buildRichTextSimple(context, '2.10.4.', S.of(context).reviewChecked),
          const SizedBox(height: 8.0),
          buildRichTextSimple(context, '2.10.4.1.', S.of(context).bonusPointsAwarded),
          const SizedBox(height: 8.0),
          buildRichTextSimple(context, '2.10.4.2.', S.of(context).bonusPointsBuyer),
          const SizedBox(height: 8.0),
          buildRichTextSimple(context, '2.10.5.', S.of(context).bonusPointsGoods),
          const SizedBox(height: 8.0),
          buildRichTextSimple(context, '2.10.6.', S.of(context).publishingReview),
        ],
      ),
    );
  }
}
