import 'package:flutter/material.dart';
import '../../../../localization/app_localizations.dart';
import '../../../../utils/constants/app_vectors.dart';
import '../../models/country_model.dart';
import 'package:flutter_svg/flutter_svg.dart';

final List<Country> countries = [
  Country('+61', 'AU', 'Австралия', 'Australia', TVectors.aus, 'AUD', 'Австралийский доллар'),
  Country('+43', 'AT', 'Австрия', 'Austria', TVectors.aut, 'EUR', 'Евро'),
  Country('+994', 'AZ', 'Азербайджан', 'Azerbaijan', TVectors.aze, 'AZN', 'Азербайджанский манат'),
  Country('+358', 'AX', 'Аландские острова', 'Åland', TVectors.ala, 'EUR', 'Евро'),
  Country('+355', 'AL', 'Албания', 'Shqipëri', TVectors.ala, 'ALL', 'Лек'),
  Country('+213', 'DZ', 'Алжир', 'Algeria', TVectors.dza, 'DZD', 'Алжирский динар'),
  Country('+1', 'AS', 'Американское Самоа', 'American Samoa', TVectors.asm, 'USD', 'Доллар США'),
  Country('+1', 'AI', 'Ангилья', 'Angullia', TVectors.aia, 'XCD', 'Восточно-карибский доллар'),
  Country('+376', 'AD', 'Андорра', 'Andorra', TVectors.and, 'EUR', 'Евро'),
  Country('+1', 'AG', 'Антигуа и Барбуда', 'Antigua & Barbuda', TVectors.atg, 'XCD', 'Восточно-карибский доллар'),
  Country('+244', 'AO', 'Ангола', 'Angola', TVectors.ago, 'AOA', 'Кванза'),
  Country('+54', 'AR', 'Аргентина', 'Argentina', TVectors.arg, 'ARS', 'Аргентинское песо'),
  Country('+374', 'AM', 'Армения', 'Հայաստան', TVectors.arm, 'AMD', 'Армянский драм'),
  Country('+297', 'AW', 'Аруба', 'Aruba', TVectors.abw, 'AWG', 'Арубанский флорин'),
  Country('+93', 'AF', 'Афганистан', 'افغانستان', TVectors.afg, 'AFN', 'Афгани'),
  Country('+973', 'BH', 'Бахрейн', 'البحرين', TVectors.bhr, 'BHD', 'Бахрейнский динар'),
  Country('+880', 'BD', 'Бангладеш', 'বাংলাদেশ', TVectors.bgd, 'BDT', 'Така'),
  Country('+880', 'BB', 'Барбадос', 'Barbados', TVectors.brb, 'BBD', 'Барбадосский доллар'),
  Country('+375', 'BY', 'Беларусь', '', TVectors.blr, 'BYN', 'Белорусский рубль'),
  Country('+32', 'BE', 'Бельгия', 'Belgiё', TVectors.bel, 'EUR', 'Евро'),
  Country('+501', 'BZ', 'Белиз', 'Belize', TVectors.blz, 'BZD', 'Белизский доллар'),
  Country('+229', 'BJ', 'Бенин', 'Bénin', TVectors.ben, 'XOF', 'Франк КФА BCEAO'),
  Country('+441', 'BM', 'Бермудские острова', 'Bermuda', TVectors.bmu, 'BMD', 'Бермудский доллар'),
  Country('+975', 'BT', 'Бутан', 'འབྲུག་ཡུལ', TVectors.btn, 'BTN', 'Нгултрум'),
  Country('+591', 'BO', 'Боливия', 'Bolivia', TVectors.bol, 'BOB', 'Боливиано'),
  Country('+535', 'BQ', 'Бонайре, Синт-Эстатиус и Саба', 'Bonaire, Sint Eustatius en Saba', TVectors.bon, 'USD', 'Доллар США'),
  Country('+387', 'BA', 'Босния и Герциговина', 'Bosna i Hercegovina', TVectors.bih, '', 'Конвертируемая марка'),
  Country('+267', 'BW', 'Ботсвана', 'Botswana', TVectors.bwa, 'BWP', 'Пула'),
  Country('+55', 'BR', 'Бразилия', 'Brasil', TVectors.bra, 'BRL', 'Бразильский реал'),
  Country('+246', 'IO', 'Британская территория Индийского океана', 'British Indian Ocean Territory', TVectors.iot, 'USD', 'Доллар США'),
  Country('+673', 'BN', 'Бруней', 'بروني', TVectors.brn, 'BND', 'брунейский доллар'),
  Country('+359', 'BG', 'Болгария', 'България', TVectors.bgr, 'BGN', 'Болгарский лев'),
  Country('+1242', 'BS', 'Багамы', 'Bahamas', TVectors.bhs, 'BSD', 'Багамский доллар'),
  Country('+226', 'BF', 'Буркина-Фасо', 'Burkina Faso', TVectors.bfa, 'XOF', 'Франк КФА BCEAO'),
  Country('+257', 'BI', 'Бурунди', 'Burundi', TVectors.bdi, 'BIF', 'Бурундийский франк'),
  Country('+47', 'BV', 'Буве остров', 'Bouvetøya', TVectors.bvt, 'NOK', 'Норвежская крона'),
  Country('+678', 'VU', 'Вануату', 'Vanuatu', TVectors.vut, 'VUV', 'Вату'),
  Country('+379', 'VA', 'Ватикан', 'Civitas Vaticana', TVectors.vat, 'EUR', 'Евро'),
  Country('+44', 'GB', 'Великобритания', 'United Kingdom', TVectors.gbr, '', ''),
  Country('+36', 'HU', 'Венгрия', 'Magyarország', TVectors.hun, '', ''),
  Country('+58', 'VE', 'Венесуэла', 'Venezuela', TVectors.ven, '', ''),
  Country('+850', 'VI', 'Виргинские Острова (США)','U.S Virgin Islands', TVectors.vir, '', ''),
  Country('+092', 'VG', 'Виргинские Острова (Великобритания)', 'British Virgin Islands', TVectors.vgb, '', ''),
  Country('+670', 'TL', 'Восточный Тимор','Timor Lorosa’e', TVectors.tls, '', ''),
  Country('+84', 'VN', 'Вьетнам', 'Việt Nam', TVectors.vnm, '', ''),
  Country('+241', 'GA', 'Габон', 'Gabon', TVectors.gab, '', ''),
  Country('+220', 'GM', 'Гамбия', 'Gambia', TVectors.gmb, '', ''),
  Country('+590', 'GP', 'Гваделупа', 'Guadeloupe', TVectors.guf, '', ''),
  Country('+995', 'GE', 'Грузия', 'საქართველო', TVectors.geo, '', ''),
  Country('+49', 'DE', 'Германия', 'Deutschland', TVectors.deu, '', ''),
  Country('+44', 'GG', 'Гернси', 'Guernsey', TVectors.ggy, '', ''),
  Country('+350', 'GI', 'Гибралтар', 'Gibraltar', TVectors.gib, '', ''),
  Country('+30', 'GR', 'Греция', 'Ελλάδα', TVectors.grc, '', ''),
  Country('+299', 'GL', 'Гренландия', 'Kalaallit Nunaat', TVectors.grl, '', ''),
  Country('+502', 'GT','Гватемала', 'Guatemala', TVectors.gtm, '', ''),
  Country('+224', 'GN', 'Гвинея', 'Guinée', TVectors.gin, '', ''),
  Country('+245', 'GW', 'Гвинея-Бисау', 'Guiné-Bissau', TVectors.gnb, '', ''),
  Country('+592', 'GY', 'Гайана', 'Guyana', TVectors.guy, '', ''),
  Country('+509', 'HT', 'Гаити', 'Haïti', TVectors.hti, '', ''),
  Country('+504', 'HN', 'Гондурас', 'Honduras', TVectors.hnd, '', ''),
  Country('+852', 'HK', 'Гонконг', '香港', TVectors.hkg, '', ''),
  Country('+473', 'GD', 'Гренада', 'Grenada', TVectors.grd, '', ''),
  Country('+995', 'GU', 'Гуам', 'Guinée', TVectors.gum, '', ''),
  Country('+45', 'DK', 'Дания', 'Danmark', TVectors.dnk, '', ''),
  Country('+832', 'JE', 'Джерси', 'Jersey', TVectors.jey, '', ''),
  Country('+253', 'DJ', 'Джибути', 'جيبوتي,', TVectors.dji, '', ''),
  Country('+1767', 'DM', 'Доминика', 'Dominica', TVectors.dma, '', ''),
  Country('+809', 'DO', 'Республика Доминикана', 'República Dominicana', TVectors.dom, '', ''),
  Country('+20', 'EG', 'Египет', 'مصر', TVectors.egy, '', ''),
  Country('+260', 'ZM', 'Замбия', 'Zambia', TVectors.zmb, '', ''),
  Country('+263', 'ZW', 'Зимбабве', 'Zimbabwe', TVectors.zwe, '', ''),
  Country('+972', 'IL', 'Израиль', '‏יִשְׂרָאֵל,', TVectors.isr, '', ''),
  Country('+91', 'IN', 'Индия', 'भारतहिंदुस्तान', TVectors.ind, '', ''),
  Country('+62', 'ID', 'Индонезия', 'Indonesia', TVectors.idn, '', ''),
  Country('+962', 'JO', 'Иордания','الأردن', TVectors.jor, '', ''),
  Country('+98', 'IR', 'Иран', 'ایران', TVectors.irn, '', ''),
  Country('+964', 'IQ', 'Ирак', 'الْعِرَاق', TVectors.irq, '', ''),
  Country('+353', 'IE', 'Ирландия','Éire', TVectors.irl, '', ''),
  Country('+354', 'IS', 'Исландия','Iceland', TVectors.isl, '', ''),
  Country('+34', 'ES', 'Испания', 'España', TVectors.esp, '', ''),
  Country('+39', 'IT', 'Италия', 'Italia', TVectors.ita, '', ''),
  Country('+967', 'YE', 'Йемен', 'ٱلْيَمَن', TVectors.yem, '', ''),
  Country('+7', 'KZ', 'Казахстан', 'Қазақстан', TVectors.kaz, '', ''),
  Country('+254', 'KE', 'Кения', 'Kenya', TVectors.ken, '', ''),
  Country('+686', 'KI', 'Кирибати', 'Kiribati', TVectors.kir, '', ''),
  Country('+855', 'KH', 'Камбоджа', 'កម្ពុជា', TVectors.khm, '', ''),
  Country('+237', 'CM', 'Камерун', 'Cameroun', TVectors.cmr, '', ''),
  Country('+1', 'CA', 'Канада', 'Canada', TVectors.can, '', ''),
  Country('+238', 'CV', 'Кабо-Верде', 'Cabo Verde', TVectors.cpv, '', ''),
  Country('+1345', 'KY', 'Каймановы Острова', 'Cayman Islands', TVectors.cym, '', ''),
  Country('+34', 'CT', 'Каталония', 'Catalunya', TVectors.cat, '', ''),
  Country('+974', 'QA', 'Катар', 'قطر', TVectors.qat, '', ''),
  Country('+86', 'CN', 'Китай', '中国', TVectors.chn, '', ''),
  Country('+506', 'CR', 'Коста-Рика', 'Costa Rica', TVectors.cri, '', ''),
  Country('+383', 'XK', 'Косово', 'Kosovё', TVectors.kos, '', ''),
  Country('+53', 'CU', 'Куба', 'Cuba', TVectors.cub, '', ''),
  Country('+599', 'CW', 'Кюрасао', 'Land Curaçao', TVectors.cuw, '', ''),
  Country('+357', 'CY', 'Кипр', 'Κύπρος', TVectors.cyp, '', ''),
  Country('+61', 'CC', 'Кокосовые острова', 'Kapelauan Cocos (Keepling)', TVectors.cck, '', ''),
  Country('+57', 'CO', 'Колумбия', 'Colombia', TVectors.col, '', ''),
  Country('+242', 'CG', 'Конго-Браззавиль', 'Congo-Brazzaville', TVectors.cog, '', ''),
  Country('+269', 'KM', 'Коморы', 'Komori', TVectors.com, '', ''),
  Country('+225', 'CI', 'Кот-д`Ивуар', 'Côte d’Ivoire', TVectors.civ, '', ''),
  Country('+965', 'KW', 'Кувейт', 'الكويت', TVectors.kwt, '', ''),
  Country('+996', 'KG', 'Киргизия', 'Кыргызстан', TVectors.kgz, '', ''),
  Country('+856', 'LA', 'Лаос', 'ລາວ', TVectors.lao, '', ''),
  Country('+371', 'LV', 'Латвия', 'Latvija', TVectors.lva, '', ''),
  Country('+961', 'LB', 'Ливан', 'لُبْنَان', TVectors.lbn, '', ''),
  Country('+266', 'LS', 'Лесото', 'Lesotho', TVectors.lso, '', ''),
  Country('+231', 'LR', 'Либерия', 'Liberia', TVectors.lbr, '', ''),
  Country('+218', 'LY', 'Ливия', 'ليبيا', TVectors.lby, '', ''),
  Country('+423', 'LI', 'Лихтенштейн', 'Liechtenstein', TVectors.lie, '', ''),
  Country('+370', 'LT', 'Литва', 'Lietuva', TVectors.ltu, '', ''),
  Country('+352', 'LU', 'Люксембург', 'Lëtzebuerg', TVectors.lux, '', ''),
  Country('+853', 'MO', 'Макао', '澳門', TVectors.mac, '', ''),
  Country('+261', 'MG', 'Мадагаскар', 'Madagasikara', TVectors.mdg, '', ''),
  Country('+265', 'MW', 'Малави', 'Malawi', TVectors.mwi, '', ''),
  Country('+212', 'MA', 'Марокко', 'المغرب', TVectors.mar, '', ''),
  Country('+60', 'MY', 'Малайзия', 'Malaysia', TVectors.mys, '', ''),
  Country('+960', 'MV', 'Мальдивы', 'ހިވެދި ގުޖޭއްރާ', TVectors.mdv, '', ''),
  Country('+223', 'ML', 'Мали','Mali', TVectors.mli, '', ''),
  Country('+356', 'MT', 'Мальта','Malta', TVectors.mlt, '', ''),
  Country('+692', 'MH', 'Маршалловы острова', 'Marshall Islands', TVectors.mhl, '', ''),
  Country('+222', 'MR', 'Мавритания', 'موريتانيا', TVectors.mrt, '', ''),
  Country('+230', 'MU', 'Маврикий', 'Mauritius', TVectors.mus, '', ''),
  Country('+262', 'YT', 'Майотта', 'Mayotte', TVectors.wlf, '', ''),
  Country('+52', 'MX', 'Мексика', 'México', TVectors.mex, '', ''),
  Country('+691', 'FM', 'Микронезия', 'Micronesia', TVectors.fsm, '', ''),
  Country('+373', 'MD', 'Молдавия', 'Moldova', TVectors.mda, '', ''),
  Country('+377', 'MC', 'Монако', 'Monaco', TVectors.mco, '', ''),
  Country('+976', 'MN', 'Монголия', 'Montserrat', TVectors.mng, '', ''),
  Country('+1664', 'MS', 'Монтсеррат', 'Монгол Улс', TVectors.msr, '', ''),
  Country('+95', 'MM', 'Мьянма (Бирма)','မြန်မာ', TVectors.mmr, '', ''),
  Country('+258', 'MZ', 'Мозамбик', 'Moçambique', TVectors.moz, '', ''),
  Country('+264', 'NA', 'Намибия', 'Namibia', TVectors.nam, '', ''),
  Country('+674', 'NR', 'Науру', 'Naoero', TVectors.nru, '', ''),
  Country('+977', 'NP', 'Непал', 'नेपाल', TVectors.npl, '', ''),
  Country('+31', 'NL', 'Нидерланды', 'Nederland', TVectors.nld, '', ''),
  Country('+687', 'NC', 'Новая Каледония', 'Nouvelle-Calédonie', TVectors.ncl, '', ''),
  Country('+64', 'NZ', 'Новая Зеландия', 'New Zealand', TVectors.nzl, '', ''),
  Country('+505', 'NI', 'Никарагуа', 'Nicaragua', TVectors.nzl, '', ''),
  Country('+227', 'NE', 'Нигер', 'Niger', TVectors.ner, '', ''),
  Country('+234', 'NG', 'Нигерия', 'Nigeria', TVectors.nga, '', ''),
  Country('+683', 'NU', 'Ниуэ', 'Niue', TVectors.niu, '', ''),
  Country('+47', 'NO', 'Норвегия', 'Norge', TVectors.nor, '', ''),
  Country('+971', 'AE', 'Объединенные Арабские Эмираты', 'الإمارات,', TVectors.are, '', ''),
  Country('+968', 'OM', 'Оман', 'عُمان', TVectors.omn, '', ''),
  Country('+247', 'AC', 'Остров Вознесения', 'Ascension Island', TVectors.asi, '', ''),
  Country('+44', 'IM', 'Остров Мэн', 'Isle of Man', TVectors.imn, '', ''),
  Country('+682', 'CK', 'Острова Кука', 'Cook Islands', TVectors.cok, '', ''),
  Country('+870', 'PN', 'Острова Питкэрн', 'Pitcairn Islands', TVectors.pcn, '', ''),
  Country('+61', 'CX', 'Остров Рождества', 'Christmas Island', TVectors.cxr, '', ''),
  Country('+290', 'SH', 'Остров Святой Елены', 'St. Elena Island', TVectors.shn, '', ''),
  Country('+599', 'KY', 'Острова Кайман', 'Cayman Islands', TVectors.cym, '', ''),
  Country('+92', 'PK', 'Пакистан', 'پاکستان', TVectors.pak, '', ''),
  Country('+970', 'PS', 'Палестина', 'دولة فلسطي', TVectors.pse, '', ''),
  Country('+680', 	'PW', 'Палау', 'Palau', TVectors.plw, '', ''),
  Country('+507', 'PA', 'Панама', 'Panamá', TVectors.pan, '', ''),
  Country('+675', 'PG', 'Папуа - Новая Гвинея', 'Papua New Guinea', TVectors.png, '', ''),
  Country('+595', 'PY', 'Парагвай', 'Paraguay', TVectors.pry, '', ''),
  Country('+51', 'PE', 'Перу', 'Perú', TVectors.per, '', ''),
  Country('+48', 'PL', 'Польша', 'Polska', TVectors.pol, '', ''),
  Country('+351', 'PT', 'Португалия', 'Portugal', TVectors.prt, '', ''),
  Country('+620', 'PR', 'Пуэрто-Рико', 'Puerto Rico', TVectors.pri, '', ''),
  Country('+262', 'RE', 'Реюньон', 'Réunion', TVectors.reu, '', ''),
  Country('+7', 'RU', 'Россия', 'Russia', TVectors.rus, '', ''),
  Country('+250', 'RW', 'Руанда', 'Rwandan', TVectors.rwa, '', ''),
  Country('+40', 'RO', 'Румыния', 'România', TVectors.rou, '', ''),
  Country('+503', 'SV', 'Сальвадор', 'El Salvador', TVectors.slv, '', ''),
  Country('+685', 'WS', 'Самоа', 'Samoa', TVectors.wsm, '', ''),
  Country('+378', 'SM', 'Сан-Марино', 'San Marino', TVectors.smr, '', ''),
  Country('+239', 'ST', 'Сан-Томе и Принсипи', 'São Tomé and Príncipe', TVectors.stp, '', ''),
  Country('+966', 'SA', 'Саудовская Аравия', 'ٱلسُّعُوْدِيَّة العربيّة', TVectors.sau, '', ''),
  Country('+389', 'MK', 'Северная Македония', 'Северна Македонија', TVectors.mkd, '', ''),
  Country('+1670', 'MP', 'Северные Марианские Острова', 'Northern Mariana Islands', TVectors.mnp, '', ''),
  Country('+590', 'BL', 'Сен-Бартелеми', 'Saint-Barthélemy', TVectors.wlf, '', ''),
  Country('+850', 'KP', 'Северная Корея', '北朝鮮', TVectors.prk, '', ''),
  Country('+221', 'SN', 'Сенегал', 'Sénégal', TVectors.sen, '', ''),
  Country('+221', 'VC', 'Сент-Винсент и Гренадины', 'St. Vincent & Grenadines', TVectors.vct, '', ''),
  Country('+659', 'KN', 'Сент-Китс и Невис', 'St. Kitts &amp; Nevis', TVectors.kna, '', ''),
  Country('+221', 'LC', 'Сент-Люсия', 'Saint Lucia', TVectors.ica, '', ''),
  Country('+381', 'RS', 'Сербия', 'Србија', TVectors.srb, '', ''),
  Country('+248', 'SC', 'Сейшельские острова', 'Sesel', TVectors.syc, '', ''),
  Country('+232', 'SL', 'Сьерра-Леоне', 'Sierra Leone', TVectors.sle, '', ''),
  Country('+65', 'SG', 'Сингапур', 'Singapura', TVectors.sgp, '', ''),
  Country('+534', 'SX', 'Синт-Мартен', 'Sint Maarten', TVectors.wlf, '', ''),
  Country('+421', 'SK', 'Словакия', 'Slovensko', TVectors.svk, '', ''),
  Country('+386', 'SI', 'Словения', 'Slovenija', TVectors.svn, '', ''),
  Country('+1', 'US', 'Соединенные Штаты Америки', 'United States of America', TVectors.usa, '', ''),
  Country('+677', 'SB', 'Соломоновы острова', 'Solomon Islands', TVectors.slb, '', ''),
  Country('+252', 'SO', 'Сомали', 'Soomaaliya', TVectors.som, '', ''),
  Country('+508', 'PM', 'Сен-Пьер и Микелон', 'Saint-Pierre et Miquelon', TVectors.spm, '', ''),
  Country('+249', 'SD', 'Судан', 'السودان', TVectors.sdn, '', ''),
  Country('+597', 'SR', 'Суринам', 'Suriname', TVectors.sur, '', ''),
  Country('+963', 'SY', 'Сирия', 'سُورِيَة', TVectors.syr, '', ''),
  Country('+886', 'TW', 'Тайвань', '台灣', TVectors.twn, '', ''),
  Country('+992', 'TJ', 'Таджикистан', 'Тоҷикистон', TVectors.tjk, '', ''),
  Country('+255', 'TZ', 'Танзания', 'Tanzania', TVectors.tza, '', ''),
  Country('+66', 'TH', 'Таиланд', 'ประเทศไทย', TVectors.tha, '', ''),
  Country('+228', 'TG', 'Того', 'Togo,', TVectors.tgo, '', ''),
  Country('+690', 'TK', 'Токелау', 'Tokelau,', TVectors.tkl, '', ''),
  Country('+676', 'TO', 'Тонга', 'Tonga', TVectors.ton, '', ''),
  Country('+1868', 'TT', 'Тринидад и Тобаго', 'Trinidad & Tobago', TVectors.tto, '', ''),
  Country('+216', 'TN', 'Тунис', 'تونس', TVectors.tun, '', ''),
  Country('+90', 'TR', 'Турция', 'Türkiye', TVectors.tur, '', ''),
  Country('+993', 'TM', 'Туркменистан', 'Türkmenistan', TVectors.tkm, '', ''),
  Country('+688', 'TV', 'Тувалу', 'Tuvalu', TVectors.tuv, '', ''),
  Country('+256', 'UG', 'Уганда', 'Uganda', TVectors.uga, '', ''),
  Country('+380', 'UA', 'Украина', 'Україна', TVectors.ukr, '', ''),
  Country('+598', 'UY', 'Уругвай', 'Uruguay', TVectors.ury, '', ''),
  Country('+998', 'UZ', 'Узбекистан', 'Oʻzbekiston', TVectors.uzb, '', ''),
  Country('+681', 'WF', 'Уоллис и Футуна', 'Wallis-et-Futuna', TVectors.wlf, '', ''),
  Country('+298', 'FO', 'Фарерские острова', '', TVectors.fro, '', ''),
  Country('+679', 'FJ', 'Фиджи', 'Fiji', TVectors.fji, '', ''),
  Country('+63', 'PH', 'Филиппины', 'Pilipinas', TVectors.phl, '', ''),
  Country('+358', 'FI', 'Финляндия', 'Suomi', TVectors.fin, '', ''),
  Country('+500', 'FK', 'Фолклендские острова', 'Falkland Islands', TVectors.flk, '', ''),
  Country('+33', 'FR', 'Франция', 'France', TVectors.fra, '', ''),
  Country('+689', 'PF', 'Французская Полинезия', 'Polynésie française', TVectors.pyf, '', ''),
  Country('+594', 'GF', 'Французская Гвиана', 'Guyane Française', TVectors.giu, '', ''),
  Country('+385', 'HR', 'Хорватия', 'Hrvatska', TVectors.hrv, '', ''),
  Country('+236', 'CF', 'Центрально-Африканская Республика', 'République Centrafricaine', TVectors.caf, '', ''),
  Country('+235', 'TD', 'Чад', 'Tchad', TVectors.tcd, '', ''),
  Country('+382', 'ME', 'Черногория', 'Црна Гора / Crna Gora', TVectors.mne, '', ''),
  Country('+420', 'CZ', 'Чехия', 'Česko', TVectors.cze, '', ''),
  Country('+56', 'CL', 'Чили', 'Chile', TVectors.chl, '', ''),
  Country('+41', 'CH', 'Швейцария', 'Schweiz', TVectors.che, '', ''),
  Country('+46', 'SE', 'Швеция', 'Sverige', TVectors.swe, '', ''),
  Country('+94', 'LK', 'Шри-Ланка', 'ශ්‍රී ලංකාව', TVectors.lka, '', ''),
  Country('+47', 'SJ', 'Шпицберген', 'Svalbard', TVectors.nor, '', ''),
  Country('+240', 'GQ', 'Экваториальная Гвинея', 'Guinea Ecuatorial', TVectors.gnq, '', ''),
  Country('+593', 'EC', 'Эквадор', 'Ecuador', TVectors.ecu, '', ''),
  Country('+291', 'ER', 'Эритрея', 'إرتريا', TVectors.eri, '', ''),
  Country('+268', 'SZ', 'Эсватини', 'Eswatini', TVectors.swz, '', ''),
  Country('+372', 'EE', 'Эстония', 'Eesti', TVectors.est, '', ''),
  Country('+251', 'ET', 'Эфиопия', 'ኢትዮጵያ', TVectors.eth, '', ''),
  Country('+27', 'ZA', 'Южная Африка', 'South Africa', TVectors.zaf, '', ''),
  Country('+82', 'KR', 'Южная Корея', '南韓', TVectors.kor, '', ''),
  Country('+211', 'SS', 'Южный Судан', 'South Sudan', TVectors.ssd, '', ''),
  Country('+876', 'JM', 'Ямайка', 'Jamaica', TVectors.jam, '', ''),
  Country('+81', 'JP', 'Япония', '日本', TVectors.jpn, '', ''),
];

Widget buildCountryList(BuildContext context) {
  final localizations = AppLocalizations.of(context);

  return ListView.builder(
    itemCount: countries.length,
    itemBuilder: (context, index) {
      final country = countries[index];
      final countryName = localizations?.translate('countries.${country.name}');

      return ListTile(
        leading: SvgPicture.asset(country.flag),
        title: Text(countryName!),
        subtitle: Text(country.nativeName),
      );
    },
  );
}

String? getCountryNameByCode(String code) {
  final country = countries.firstWhere((country) => country.code.replaceAll('+', '') == code.replaceAll('+', ''),
    orElse: () => Country('', '', '', '', '', '', ''),
  );
  return country.name.isNotEmpty ? country.name : null;
}
