import 'package:flutter/material.dart';
import '../../../../../common/widgets/texts/rich_helper_text.dart';
import '../../../../../generated/l10n/l10n.dart';

class PrivacyProduceConditions extends StatelessWidget {
  const PrivacyProduceConditions({super.key});

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.all(8.0),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          buildRichTextSimple(context, '5.1.', S.of(context).companyProcessesEnsures),
          const SizedBox(height: 8.0),
          buildRichTextSimple(context, '5.2.', S.of(context).processesAutomationTools),
          const SizedBox(height: 8.0),
          buildRichTextSimple(context, '5.3.', S.of(context).registeredUserConsents),
          const SizedBox(height: 8.0),
          buildRichTextSimple(context, '5.4.', S.of(context).notProcessSpecialCategories),
          const SizedBox(height: 8.0),
          buildRichTextSimple(context, '5.5.', S.of(context).rightEntrustProcessing),
          const SizedBox(height: 8.0),
          buildRichTextSimple(context, '5.6.', S.of(context).personsProcessingPersonal),
          const SizedBox(height: 8.0),
          buildRichTextSimple(context, '5.7.', S.of(context).entrustProcessingPersonal),
          const SizedBox(height: 8.0),
          buildRichTextSimple(context, '5.7.1.', S.of(context).deliveryOrdersReturnGoods),
          const SizedBox(height: 8.0),
          buildRichTextSimple(context, '5.7.2.', S.of(context).receiptProcessingTransfer),
          const SizedBox(height: 8.0),
          buildRichTextSimple(context, '5.7.3.', S.of(context).carryingCustomsClearance),
          const SizedBox(height: 8.0),
          buildRichTextSimple(context, '5.7.4.', S.of(context).groundTransportTickets),
          const SizedBox(height: 8.0),
          buildRichTextSimple(context, '5.7.5.', S.of(context).completingTrainingCourses),
          const SizedBox(height: 8.0),
          buildRichTextSimple(context, '5.8.', S.of(context).policiesInstructionsTransfer),
          const SizedBox(height: 8.0),
          buildRichTextSimple(context, '5.9.', S.of(context).obligesPersonsAuthorized),
          const SizedBox(height: 8.0),
          buildRichTextSimple(context, '5.10.', S.of(context).destroyingPersonalData),
          const SizedBox(height: 8.0),
          buildRichTextSimple(context, '5.11.', S.of(context).companyNotVerify),
          const SizedBox(height: 8.0),
          buildRichTextSimple(context, '5.12.', S.of(context).controlComplianceTerms),
          const SizedBox(height: 8.0),
          buildRichTextSimple(context, '5.13.', S.of(context).representativesAuthorized),
          const SizedBox(height: 8.0),
          buildRichTextSimple(context, '5.14.', S.of(context).companyNecessaryLegal),
          const SizedBox(height: 8.0),
          buildRichTextSimple(context, '5.14.1.', S.of(context).determiningThreatsSecurity),
          const SizedBox(height: 8.0),
          buildRichTextSimple(context, '5.14.2.', S.of(context).applicationOrganizational),
          const SizedBox(height: 8.0),
          buildRichTextSimple(context, '5.14.3.', S.of(context).assessingEffectiveness),
          const SizedBox(height: 8.0),
          buildRichTextSimple(context, '5.14.4.', S.of(context).appointmentPersonResponsible),
          const SizedBox(height: 8.0),
          buildRichTextSimple(context, '5.14.5.', S.of(context).publicationCompanyDocuments),
          const SizedBox(height: 8.0),
          buildRichTextSimple(context, '5.14.6.', S.of(context).carryingInternalControl),
          const SizedBox(height: 8.0),
          buildRichTextSimple(context, '5.14.7.', S.of(context).familiarizationCompanys),
          const SizedBox(height: 8.0),
          buildRichTextSimple(context, '5.14.8.', S.of(context).assessmentAccordance),
          const SizedBox(height: 8.0),
          buildRichTextSimple(context, '5.14.9.', S.of(context).detectionFactsUnauthorized),
          const SizedBox(height: 8.0),
          buildRichTextSimple(context, '5.14.10.', S.of(context).controlSecurityPersonalData),
          const SizedBox(height: 8.0),
          buildRichTextSimple(context, '5.15.', S.of(context).companyStops),
          const SizedBox(height: 8.0),
          buildRichTextSimple(context, '-', S.of(context).liquidationCompany),
          const SizedBox(height: 8.0),
          buildRichTextSimple(context, '-', S.of(context).reorganizationCompany),
          const SizedBox(height: 8.0),
          buildRichTextSimple(context, '-', S.of(context).terminationLegalGrounds),
          const SizedBox(height: 8.0),
          buildRichTextSimple(context, '-', S.of(context).revocationConsentSubject),
          const SizedBox(height: 8.0),
          buildRichTextSimple(context, '5.16.', S.of(context).storagePersonalData),
          const SizedBox(height: 8.0),
          buildRichTextSimple(context, '5.17.', S.of(context).collectingPersonalData),
          const SizedBox(height: 8.0),
          buildRichTextSimple(context, '5.18.', S.of(context).procedureDestruction),
          const SizedBox(height: 8.0),
          buildRichTextSimple(context, '5.19.', S.of(context).deletePersonalAccount),
        ],
      ),
    );
  }
}
