import 'package:flutter/material.dart';
import '../../../../../common/widgets/texts/rich_helper_text.dart';
import '../../../../../generated/l10n/l10n.dart';

class PrivacyGenerationProvision extends StatelessWidget {
  const PrivacyGenerationProvision({super.key});

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.all(8.0),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          buildRichTextSimple(context, '1.1.', S.of(context).termsPrivacy),
          const SizedBox(height: 8.0),
          buildRichTextSimple(context, '1.2.', S.of(context).processesPersonalAccordance),
          const SizedBox(height: 8.0),
          buildRichTextSimple(context, '1.3.', S.of(context).policyAppliesSubjects),
          const SizedBox(height: 8.0),
          buildRichTextSimple(context, '1.4.', S.of(context).policyAppliesRelated),
          const SizedBox(height: 8.0),
          buildRichTextSimple(context, '1.5.', S.of(context).subjectPersonalPolicy),
          const SizedBox(height: 8.0),
          buildRichTextSimple(context, '1.6.', S.of(context).processingPersonalCarried),
          const SizedBox(height: 8.0),
          buildRichTextSimple(context, '1.7.', S.of(context).policyComesGeneralDirector),
          const SizedBox(height: 8.0),
          buildRichTextSimple(context, '1.8.', S.of(context).companyUnilaterallyChange),
          const SizedBox(height: 8.0),
          buildRichTextSimple(context, '1.9.', S.of(context).policyFreelyInternet),
          const SizedBox(height: 8.0),
          buildRichTextSimple(context, '1.10.', S.of(context).policyAppliesReceived),
          const SizedBox(height: 8.0),
          buildRichTextSimple(context, '1.11.', S.of(context).internalControlCompany),
          const SizedBox(height: 8.0),
          buildRichTextSimple(context, '1.12.', S.of(context).followingTermsPolicy),
          const SizedBox(height: 8.0),
          buildRichTextSimple(context, '1.12.1.', S.of(context).automatedProcessingPersonal),
          const SizedBox(height: 8.0),
          buildRichTextSimple(context, '1.12.2.', S.of(context).blockingTemporaryCessation),
          const SizedBox(height: 8.0),
          buildRichTextSimple(context, '1.12.3.', S.of(context).securityPersonalData),
          const SizedBox(height: 8.0),
          buildRichTextSimple(context, '1.12.4.', S.of(context).biometricPersonalData),
          const SizedBox(height: 8.0),
          buildRichTextSimple(context, '1.12.5.', S.of(context).federalLaw),
          const SizedBox(height: 8.0),
          buildRichTextSimple(context, '1.12.6.', S.of(context).registeredBuyer),
          const SizedBox(height: 8.0),
          buildRichTextSimple(context, '1.12.7.', S.of(context).depersonalization),
          const SizedBox(height: 8.0),
          buildRichTextSimple(context, '1.12.8.', S.of(context).processingPersonalData),
          const SizedBox(height: 8.0),
          buildRichTextSimple(context, '1.12.9.', S.of(context).society),
          const SizedBox(height: 8.0),
          buildRichTextSimple(context, '1.12.10.', S.of(context).operatorIndependently),
          const SizedBox(height: 8.0),
          buildRichTextSimple(context, '1.12.11.', S.of(context).confidentialityPersonalData),
          const SizedBox(height: 8.0),
          buildRichTextSimple(context, '1.12.12.', S.of(context).personalDataIdentified),
          const SizedBox(height: 8.0),
          buildRichTextSimple(context, '1.12.13.', S.of(context).individualUsingServices),
          const SizedBox(height: 8.0),
          buildRichTextSimple(context, '1.12.14.', S.of(context).websiteCompanyInformation),
          const SizedBox(height: 8.0),
          buildRichTextSimple(context, '1.12.15.', S.of(context).specialCategoryPersonalData),
          const SizedBox(height: 8.0),
          buildRichTextSimple(context, '1.12.16.', S.of(context).provisionActionsAimed),
          const SizedBox(height: 8.0),
          buildRichTextSimple(context, '1.12.17.', S.of(context).distributionActionsAimed),
          const SizedBox(height: 8.0),
          buildRichTextSimple(context, '1.12.18.', S.of(context).individualDirectly),
          const SizedBox(height: 8.0),
          buildRichTextSimple(context, '1.12.19.', S.of(context).destructionPersonalData),
          const SizedBox(height: 8.0),
          buildRichTextSimple(context, '1.12.20.', S.of(context).cookiesCompanyContaining),
          const SizedBox(height: 8.0),
          buildRichTextSimple(context, '1.12.21.', S.of(context).nicknameWebsite),
          const SizedBox(height: 8.0),
          buildRichTextSimple(context, '1.13.', S.of(context).otherTermsNotMentioned),
        ],
      ),
    );
  }
}
